import React from 'react';
import { now, DAY, HOUR } from '@crateline/domain/clock.js';
import { CATEGORIES, SUBS } from '@crateline/domain/data.js';
import { fmtMoney, toC, can, roleOf, assignment, key, orderBuckets, storeBuckets, refundableC, paidC, refundedC, S, verifyPayoutMethod } from '@crateline/domain/fin.js';
import { fmtDT, fmtDate, rel, fmtN, STATUS_LABEL, STATUS_TONE, isOverdue, openCase, deliveredQty, startPrice, money, completePurchase } from '@crateline/domain/logic.js';
import { Icon, Btn, Badge, Avatar, Modal, Field, Notice, Empty, Table, KV, Section, Stat, Sim, Timeline, FileChip, ProductArt, Seg, useApp } from './ui.jsx';
import { M, TS, useGate, PageTitle, AList, DetailHead, DTabs, DetailGrid, SidePanel, ReasonDialog, Evidence, AuditTrail, ExportButton, ROUTES } from './admin-ui.jsx';
import * as O from '@crateline/domain/ops.js';
import { apiEnabled } from './api.js';
const { useState, useMemo, useEffect } = React;

const CASE_T = { Open: 'warn', 'Awaiting seller': 'warn', 'Awaiting buyer': 'info', Escalated: 'bad', Resolved: 'ok', Closed: 'muted' };
const PAY_T = { Paid: 'ok', Failed: 'bad', Expired: 'muted', Processing: 'warn', Cancelled: 'muted', 'Awaiting payment': 'info' };
const name = (db, uid) => db.users[uid]?.name || '—';
const staffName = (db, id) => id ? db.staff[id]?.name : 'Unassigned';
const maskEmail = e => e ? e.replace(/^(.)(.*)(@.*)$/, (m, a, b, c) => a + '•••' + c) : '';

// ---------- queue model (derived from records, never hard-coded)
export function queueItems(db, staff) {
  const out = []; const add = (perm, x) => { if (can(db, staff, perm)) { const a = assignment(db, x.k); out.push({ ...x, id: x.k, assigneeId: a.assigneeId, priority: a.priority !== 'Normal' ? a.priority : (x.priority || 'Normal'), overdue: x.deadline && x.deadline < now() }); } };
  db.verifications.filter(v => v.state === 'Verification pending').forEach(v => { const st = db.stores[v.storeId]; add('sellers.view', { k: key('seller', st.id), type: 'Seller review', ref: v.id, subject: st.name, party: name(db, st.ownerId), since: v.submittedAt, deadline: v.submittedAt + 2 * DAY, next: 'Review verification', route: { page: 'a-seller', id: st.id } }); });
  db.listings.filter(l => l.availability === 'Pending review').forEach(l => add('catalog.view', { k: key('listing', l.id), type: 'Listing review', ref: l.id, subject: l.title, party: db.stores[l.storeId].name, since: l.submittedAt, deadline: l.submittedAt + DAY, next: 'Moderate listing', route: { page: 'a-product', id: l.id } }));
  db.reports.filter(r => r.status === 'Open').forEach(r => add('catalog.view', { k: key('listing', r.listingId), type: 'Product report', ref: r.id, subject: r.reason, party: db.stores[db.listings.find(l => l.id === r.listingId).storeId].name, since: r.at, deadline: r.at + 2 * DAY, next: 'Review report', route: { page: 'a-product', id: r.listingId } }));
  db.orders.filter(o => isOverdue(o)).forEach(o => add('orders.view', { k: key('order', o.id), type: 'Overdue order', ref: o.id, subject: o.snap.title, party: `${name(db, o.buyerId)} / ${o.snap.storeName}`, amountC: toC(o.total), since: o.dueAt, deadline: o.dueAt, priority: 'High', next: 'Investigate delay', route: { page: 'a-order', id: o.id } }));
  db.cases.filter(c => !['Resolved', 'Closed'].includes(c.status)).forEach(c => { const o = db.orders.find(x => x.id === c.orderId); add('cases.view', { k: key('case', c.id), type: 'Dispute', ref: c.id, subject: c.reason, party: `${name(db, c.buyerId)} / ${db.stores[c.storeId].name}`, amountC: toC(o.total), since: c.openedAt, deadline: c.deadline, priority: c.status === 'Escalated' ? 'Urgent' : 'Normal', next: c.remedy ? `Remedy: ${c.remedy.state}` : 'Review and decide', route: { page: 'a-case', id: c.id } }); });
  db.refunds.filter(r => ['Requested', 'Approved', 'Failed', 'Reconciliation required'].includes(r.status)).forEach(r => add('refunds.view', { k: key('refund', r.id), type: 'Refund request', ref: r.id, subject: `${r.orderId} · ${r.reason}`, party: name(db, db.orders.find(o => o.id === r.orderId).buyerId), amountC: r.amountC, since: r.createdAt, deadline: r.createdAt + 2 * DAY, next: { Requested: 'Independent approval', Approved: 'Execute (Finance)', Failed: 'Retry after review', 'Reconciliation required': 'Reconcile' }[r.status], route: { page: 'a-refund', id: r.id } }));
  db.payouts.filter(p => ['Awaiting approval', 'Approved', 'Reconciliation required', 'Failed'].includes(p.status)).forEach(p => add('payouts.view', { k: key('payout', p.id), type: p.status === 'Awaiting approval' || p.status === 'Approved' ? 'Payout request' : 'Payout exception', ref: p.id, subject: p.dest, party: db.stores[p.storeId].name, amountC: p.amountC, since: p.requestedAt, deadline: p.requestedAt + 2 * DAY, next: { 'Awaiting approval': 'Independent approval', Approved: 'Execute transfer', 'Reconciliation required': 'Reconcile transfer', Failed: 'Review failure' }[p.status], route: { page: 'a-payout', id: p.id } }));
  db.tickets.filter(t => !['Resolved', 'Closed'].includes(t.status)).forEach(t => add('support.view', { k: key('ticket', t.id), type: 'Support ticket', ref: t.id, subject: t.subject, party: t.name, since: t.at, deadline: t.deadline, priority: t.priority, next: t.status === 'Awaiting customer' ? 'Wait for customer' : 'Reply', route: { page: 'a-ticket', id: t.id } }));
  db.recon.filter(r => r.status === 'Open').forEach(r => add('payments.view', { k: key('recon', r.id), type: 'Reconciliation', ref: r.id, subject: r.type, party: r.paymentId || r.ref, amountC: r.amountC, since: r.at, deadline: r.at + DAY, next: 'Reconcile', route: { page: 'a-recon' } }));
  return out;
}
const PRI = { Urgent: 0, High: 1, Normal: 2, Low: 3 };
const queueSort = (a, b) => (b.overdue - a.overdue) || (PRI[a.priority] - PRI[b.priority]) || (a.since - b.since);

export function AOverview() {
  const { db, staff, nav, listState } = useApp(); const g = useGate(['ov']); const [range, setRange] = useState(7); const [team, setTeam] = useState('');
  const items = useMemo(() => queueItems(db, staff), [db, staff]); if (g) return g;
  const inTeam = items.filter(i => !team || (i.assigneeId && db.staff[i.assigneeId]?.team === team) || (team === 'Unassigned' && !i.assigneeId));
  const cnt = t => inTeam.filter(i => i.type === t).length;
  const go = type => { listState.current['queue'] = { q: '', f: { type }, sort: 'default', page: 0, sel: [] }; nav({ page: 'a-queue' }); };
  const since = now() - range * DAY; const inRange = ts => ts >= since;
  const teams = [...new Set(Object.values(db.staff).map(s => s.team))];
  const cards = [['Seller review', 'Pending seller reviews', 'store'], ['Listing review', 'Listings awaiting review', 'box'], ['Overdue order', 'Overdue orders', 'flag'], ['Dispute', 'Open disputes', 'scale'], ['Refund request', 'Refund requests', 'refresh'], ['Payout exception', 'Payout exceptions', 'alert'], ['Payout request', 'Payout requests', 'bank'], ['Support ticket', 'Support tickets needing attention', 'headset'], ['Reconciliation', 'Reconciliation items', 'wallet']].filter(([t]) => items.some(i => i.type === t) || can(db, staff, { 'Seller review': 'sellers.view', 'Listing review': 'catalog.view', 'Overdue order': 'orders.view', Dispute: 'cases.view', 'Refund request': 'refunds.view', 'Payout exception': 'payouts.view', 'Payout request': 'payouts.view', 'Support ticket': 'support.view', Reconciliation: 'payments.view' }[t]));
  return <>
    <div className="dash-top">
      <section className="discover" aria-labelledby="ov-h">
        <div className="row-between"><span className="eyebrow">{roleOf(db, staff).name}</span>
          <select aria-label="Team" value={team} onChange={e => setTeam(e.target.value)} style={{ width: 'auto' }}><option value="">All teams</option><option>Unassigned</option>{teams.map(t => <option key={t}>{t}</option>)}</select></div>
        <h1 id="ov-h">Operations overview</h1>
        <p className="lead">Current backlog for your role. Select a figure to open that part of the work queue.</p>
        {cards.length ? <div className="dash-figs">{cards.map(([t, l]) => { const n = cnt(t); const late = inTeam.filter(i => i.type === t && i.overdue).length;
          return <button key={t} className="dash-fig" onClick={() => go(t)}><b>{n}</b><span>{l}</span>{late > 0 && <Badge tone="bad">{late} overdue</Badge>}</button>; })}</div>
          : <Empty title="No queues for your role" />}
      </section>
      <section className="dash-side" aria-labelledby="rq-h">
        <div className="row-between"><h2 id="rq-h">Review queue</h2><button className="linkbtn" onClick={() => nav({ page: 'a-queue' })}>Open work queue</button></div>
        {inTeam.length ? <ul className="rlist">{inTeam.slice().sort(queueSort).slice(0, 6).map(i => <li key={i.k}><button onClick={() => nav(i.route)}>
          <span className="rl-ic" aria-hidden="true"><Icon n={(cards.find(c => c[0] === i.type) || [])[2] || 'list'} s={17} /></span>
          <div className="rl-main"><span className="rl-t">{i.ref} · {i.subject}</span><span className="muted xs">{i.type} · waiting {rel(i.since).replace(' ago', '')} · {staffName(db, i.assigneeId)}</span></div>
          {i.overdue ? <Badge tone="bad">Overdue</Badge> : <span className="rl-go" aria-hidden="true"><Icon n="right" s={14} /></span>}</button></li>)}</ul>
          : <p className="muted small">Nothing waiting.</p>}
      </section>
    </div>
    <div className="row-between"><h2 className="sec-h">Activity in period</h2><Seg label="Period" value={range} onChange={setRange} options={[{ id: 1, label: '24 h' }, { id: 7, label: '7 days' }, { id: 30, label: '30 days' }]} /></div>
    <div className="stats">
      {can(db, staff, 'orders.view') && <Stat label="Paid orders placed" value={db.orders.filter(o => o.payment.status === 'Paid' && inRange(o.placedAt)).length} sub={`${new Set(db.orders.filter(o => o.payment.status === 'Paid' && inRange(o.placedAt)).map(o => o.purchaseRef)).size} purchase groups`} />}
      {can(db, staff, 'cases.view') && <Stat label="Cases opened" value={db.cases.filter(c => inRange(c.openedAt)).length} />}
      {can(db, staff, 'refunds.view') && <Stat label="Refunds confirmed" value={fmtMoney(db.refunds.filter(r => r.confirmedAt && inRange(r.confirmedAt)).reduce((a, r) => a + r.amountC, 0))} sub="USD" />}
      {can(db, staff, 'payouts.view') && <Stat label="Payouts paid" value={fmtMoney(db.payouts.filter(p => p.paidAt && inRange(p.paidAt)).reduce((a, p) => a + p.amountC, 0))} sub="USD" />}
      {can(db, staff, 'support.view') && <Stat label="Tickets created" value={db.tickets.filter(t => inRange(t.at)).length} />}
    </div>
  </>;
}

export function AQueue() {
  const { db, staff, nav, perform } = useApp(); const g = useGate(['q']); const items = useMemo(() => queueItems(db, staff), [db, staff]); const [esc, setEsc] = useState(null); if (g) return g;
  const types = [...new Set(items.map(i => i.type))];
  return <>
    <PageTitle title="Work queue" sub="Overdue first, then priority, then time waiting. Financial and verification decisions are reviewed individually." actions={<ExportButton name="Work queue" rows={items} cols={[['Reference', r => r.ref], ['Type', r => r.type], ['Subject', r => r.subject], ['Assigned', r => staffName(db, r.assigneeId)], ['Priority', r => r.priority], ['Deadline', r => fmtDT(r.deadline)]]} />} />
    <AList id="queue" rows={items} search={i => `${i.ref} ${i.subject} ${i.party}`} onOpen={i => nav(i.route)}
      filters={[{ k: 'type', label: 'Type', options: types.map(t => [t, t]), test: (i, v) => i.type === v }, { k: 'assignee', label: 'Assignment', options: [['me', 'Assigned to me'], ['none', 'Unassigned'], ['other', 'Assigned to others']], test: (i, v) => v === 'me' ? i.assigneeId === staff.id : v === 'none' ? !i.assigneeId : i.assigneeId && i.assigneeId !== staff.id }, { k: 'deadline', label: 'Deadline', options: [['overdue', 'Overdue'], ['24h', 'Due in 24 h']], test: (i, v) => v === 'overdue' ? i.overdue : i.deadline && i.deadline - now() < DAY && !i.overdue }]}
      sorts={[{ id: 'default', label: 'Overdue, priority, waiting', fn: queueSort }, { id: 'deadline', label: 'Deadline soonest', fn: (a, b) => (a.deadline || 9e15) - (b.deadline || 9e15) }, { id: 'amount', label: 'Amount', fn: (a, b) => (b.amountC || 0) - (a.amountC || 0) }]}
      bulk={can(db, staff, 'queue.assign') ? [{ label: 'Assign to me', run: ids => perform('assignMany', { keys: ids, staffId: staff.id }, d => ids.forEach(k => O_assign(d, staff, k, staff.id)), `${ids.length} assigned to you`) }, { label: 'Unassign', run: ids => perform('assignMany', { keys: ids, staffId: null }, d => ids.forEach(k => O_assign(d, staff, k, null)), 'Unassigned') }] : null}
      cols={[{ k: 'ref', label: 'Reference', render: i => <><b>{i.ref}</b><span className="xs muted block">{i.type}</span></> }, { k: 's', label: 'Subject', render: i => <span className="trunc2 small">{i.subject}</span> }, { k: 'p', label: 'Buyer or seller', render: i => <span className="small">{i.party}</span> },
        { k: 'a', label: 'Amount', cls: 'num', render: i => i.amountC != null ? <M c={i.amountC} /> : '—' }, { k: 'pr', label: 'Priority', render: i => <Badge tone={{ Urgent: 'bad', High: 'warn' }[i.priority] || 'muted'}>{i.priority}</Badge> },
        { k: 'as', label: 'Assigned', render: i => <span className="small">{staffName(db, i.assigneeId)}</span> }, { k: 'w', label: 'Waiting', render: i => rel(i.since).replace(' ago', '') },
        { k: 'dl', label: 'Deadline', render: i => i.deadline ? <span className={i.overdue ? 'bad-t' : ''}>{rel(i.deadline)}</span> : '—' }, { k: 'n', label: 'Next action', render: i => <span className="small">{i.next}</span> },
        { k: 'x', label: '', render: i => <div className="row-acts">{!i.assigneeId && <Btn size="sm" v="ghost" onClick={() => perform('claim', { key: i.k }, d => O_assign(d, staff, i.k, staff.id), 'Claimed')}>Claim</Btn>}<Btn size="sm" v="ghost" onClick={() => setEsc(i)}>Escalate</Btn></div> }]} />
    {esc && <ReasonDialog title={`Escalate ${esc.ref}`} intro="Sets priority to Urgent and notifies staff who can assign work." confirm="Escalate" onClose={() => setEsc(null)} onSubmit={v => perform('escalateWork', { key: esc.k, reason: v.reason }, d => escalateWork(d, d.staff[staff.id], esc.k, v.reason), 'Escalated')} />}
  </>;
}
import { setAssignee, snotify, staffWith, audit, escalateWork } from '@crateline/domain/fin.js';
function O_assign(d, staff, k, to) { setAssignee(d, d.staff[staff.id], k, to, to ? 'Bulk assignment' : 'Bulk unassign', k.split(':')[1]); }

// ---------- users
export function AUsers() {
  const { db, staff, nav } = useApp(); const g = useGate(['u']); if (g) return g;
  const users = Object.values(db.users);
  const row = u => ({ ...u, orders: db.orders.filter(o => o.buyerId === u.id && o.payment.status === 'Paid').length, cases: db.cases.filter(c => c.buyerId === u.id && !['Resolved', 'Closed'].includes(c.status)).length, state: (u.restrictions || []).some(r => r.active) ? 'Restricted' : u.deletion ? 'Closure requested' : 'Active' });
  const rows = users.map(row);
  return <><PageTitle title="Users" sub="Buyer and seller accounts. Contact details are masked; passwords and recovery codes are never shown." actions={<ExportButton name="Users" rows={rows} cols={[['Account', r => r.acct], ['Name', r => r.name], ['State', r => r.state], ['Orders', r => r.orders]]} />} />
    <AList id="users" rows={rows} search={u => `${u.acct} ${u.username} ${u.name} ${u.email}`} onOpen={u => nav({ page: 'a-user', id: u.id })}
      filters={[{ k: 'state', label: 'State', options: [['Active', 'Active'], ['Restricted', 'Restricted'], ['Closure requested', 'Closure requested']], test: (u, v) => u.state === v }, { k: 'seller', label: 'Type', options: [['b', 'Buyers'], ['s', 'Sellers']], test: (u, v) => v === 's' ? !!u.storeId : !u.storeId }]}
      sorts={[{ id: 'joined', label: 'Newest', fn: (a, b) => b.joined - a.joined }, { id: 'name', label: 'Name', fn: (a, b) => a.name.localeCompare(b.name) }]}
      cols={[{ k: 'acct', label: 'Account', render: u => <b>{u.acct}</b> }, { k: 'n', label: 'Name', render: u => <><span>{u.name}</span><span className="xs muted block">@{u.username}{u.storeId ? ' · seller' : ''}</span></> }, { k: 'e', label: 'Email', render: u => <span className="small">{maskEmail(u.email)}</span> },
        { k: 's', label: 'State', render: u => <Badge tone={u.state === 'Active' ? 'ok' : 'warn'}>{u.state}</Badge> }, { k: 'j', label: 'Joined', render: u => fmtDate(u.joined) }, { k: 'o', label: 'Orders', cls: 'num', render: u => u.orders }, { k: 'c', label: 'Open cases', cls: 'num', render: u => u.cases }, { k: 'l', label: 'Last active', render: u => rel(u.lastActive) }]} /></>;
}
export function AUser() {
  const { db, staff, route, nav, act, perform } = useApp(); const g = useGate(['u', route.id]); const [dlg, setDlg] = useState(null); if (g) return g;
  const u = db.users[route.id]; if (!u) return <Empty title="User not found" />;
  const orders = db.orders.filter(o => o.buyerId === u.id); const cases = db.cases.filter(c => c.buyerId === u.id); const tickets = db.tickets.filter(t => t.userId === u.id); const st = u.storeId && db.stores[u.storeId];
  const active = (u.restrictions || []).filter(r => r.active);
  return <>
    <DetailHead back={{ label: 'Users', route: { page: 'a-users' } }} refId={u.acct} title={u.name} badges={<>{active.map(r => <Badge key={r.id} tone="warn">Restricted: {r.scope}</Badge>)}{!active.length && <Badge tone="ok">Active</Badge>}{u.deletion && <Badge tone="info">Closure requested</Badge>}{st && <Badge tone="muted">Seller: {st.name}</Badge>}</>}
      actions={<><Btn icon="lock" disabled={!can(db, staff, 'users.restrict')} onClick={() => setDlg('restrict')}>Restrict</Btn><Btn icon="mail" disabled={!can(db, staff, 'users.contact')} onClick={() => setDlg('recovery')}>Send recovery link</Btn>{u.deletion && <Btn disabled={!can(db, staff, 'users.restrict')} onClick={() => setDlg('closure')}>Review closure</Btn>}</>} />
    <DetailGrid main={<DTabs tabs={[
      { id: 'ov', label: 'Profile', body: <Section><KV items={[['Username', '@' + u.username], ['Email', maskEmail(u.email) + (u.emailVerified ? ' (verified)' : ' (unverified)')], ['Phone', u.phone ? u.phone.replace(/\d(?=\d{3})/g, '•') : '—'], ['Telegram', u.telegram || '—'], ['Two-factor', u.twoFA ? 'On' : 'Off'], ['Joined', fmtDate(u.joined)], ['Password and recovery codes', 'Never visible to staff']]} />
        <p className="xs muted">Private conversations are not shown here. Access requires a linked case or ticket and evidence permission.</p></Section> },
      { id: 'orders', label: 'Purchases', count: orders.length, body: <Table rows={orders} onRow={o => can(db, staff, 'orders.view') && nav({ page: 'a-order', id: o.id })} empty={<Empty title="No purchases" />} cols={[{ k: 'id', label: 'Order', render: o => <b>{o.id}</b> }, { k: 's', label: 'Status', render: o => <Badge tone={STATUS_TONE[o.status]}>{STATUS_LABEL[o.status]}</Badge> }, { k: 'p', label: 'Payment', render: o => o.payment.status }, { k: 'a', label: 'Amount', cls: 'num', render: o => money(o.total) }]} /> },
      { id: 'cases', label: 'Cases and tickets', count: cases.length + tickets.length, body: <Section>{cases.map(c => <div key={c.id} className="pv-row"><b>{c.id}</b><Badge tone={CASE_T[c.status]}>{c.status}</Badge><span className="small">{c.reason}</span></div>)}{tickets.map(t => <div key={t.id} className="pv-row"><b>{t.id}</b><Badge tone="muted">{t.status}</Badge><span className="small">{t.subject}</span></div>)}{!cases.length && !tickets.length && <p className="muted small">None.</p>}</Section> },
      { id: 'restr', label: 'Restrictions', count: (u.restrictions || []).length, body: <Section>{(u.restrictions || []).length ? (u.restrictions || []).map(r => <div key={r.id} className="restr"><div className="row-gap"><Badge tone={r.active ? 'warn' : 'muted'}>{r.scope}</Badge><b className="small">{r.active ? 'Active' : 'Ended'}</b><span className="xs muted">by {r.by} · {fmtDT(r.at)}{r.expiresAt ? ' · expires ' + fmtDT(r.expiresAt) : ''}</span></div><p className="small">{r.reason}</p><p className="xs muted">Shown to user: {r.notice}</p>{r.active && can(db, staff, 'users.restrict') && <Btn size="sm" onClick={() => setDlg({ restore: r })}>Restore</Btn>}</div>) : <p className="muted small">No restrictions.</p>}
        <p className="xs muted">Suspended users keep access to existing orders, cases and support. A selling restriction does not block buying.</p></Section> },
      { id: 'tl', label: 'Activity', body: <Section><AuditTrail objects={[u.acct, u.id]} /></Section> },
    ]} />} side={<>{u.deletion && <Section title="Closure request"><KV items={[['Requested', fmtDT(u.deletion.at)], ['Blockers', O.closureBlockers(db, u.id).join(', ') || 'None'], u.deletion.state && ['State', u.deletion.state]]} /></Section>}<SidePanel k={key('user', u.id)} label={u.acct} /></>} />
    {dlg === 'restrict' && <ReasonDialog title={`Restrict ${u.name}`} confirm="Apply restriction" danger fields={[{ k: 'scope', label: 'Scope', type: 'select', options: [['purchases', 'New purchases'], ['messages', 'New messages'], ...(u.storeId ? [['selling', 'Seller activity']] : [])], initial: 'purchases' }, { k: 'days', label: 'Expiry (days, optional)', type: 'number' }, { k: 'notice', label: 'Notification text shown to the user', type: 'textarea', required: true }]} onClose={() => setDlg(null)} onSubmit={v => perform('restrictUser', { userId: u.id, scope: v.scope, reason: v.reason, days: +v.days || 0, notice: v.notice }, d => O.restrictUser(d, staff, u.id, { scope: v.scope, reason: v.reason, days: +v.days || 0, notice: v.notice }), 'Restriction applied')} />}
    {dlg?.restore && <ReasonDialog title={`Restore ${dlg.restore.scope}`} confirm="Restore" onClose={() => setDlg(null)} onSubmit={v => perform('restoreUser', { userId: u.id, restrictionId: dlg.restore.id, reason: v.reason }, d => O.restoreUser(d, staff, u.id, dlg.restore.id, v.reason), 'Restriction lifted')} />}
    {dlg === 'recovery' && <ReasonDialog title="Send password recovery" intro="The user receives a simulated recovery link. Staff never choose or see passwords." confirm="Send link" onClose={() => setDlg(null)} onSubmit={v => perform('sendRecovery', { userId: u.id, reason: v.reason }, d => O.sendRecovery(d, staff, u.id, v.reason), 'Recovery link sent (simulated)')} />}
    {dlg === 'closure' && <ReasonDialog title="Progress closure request" intro={O.closureBlockers(db, u.id).length ? `Blocked by: ${O.closureBlockers(db, u.id).join(', ')}. The user will be told what remains.` : 'No blockers. Transaction records are retained or anonymised under the retention policy; nothing is deleted here.'} confirm={O.closureBlockers(db, u.id).length ? 'Explain blockers to user' : 'Approve closure'} onClose={() => setDlg(null)} onSubmit={v => perform('progressClosure', { userId: u.id, reason: v.reason }, d => O.progressClosure(d, staff, u.id, v.reason), 'Closure request updated')} />}
  </>;
}

// ---------- sellers
export function ASellers() {
  const { db, nav } = useApp(); const g = useGate(['s']); if (g) return g;
  const rows = Object.values(db.stores).map(s => { const v = db.verifications.find(x => x.storeId === s.id); return { ...s, v, submitted: v?.submittedAt, outstanding: v?.missing || [], reviewer: assignment(db, key('seller', s.id)).assigneeId }; });
  return <><PageTitle title="Sellers" sub="Verification queue and store oversight. Identity images never appear in this list." />
    <AList id="sellers" rows={rows} search={s => `${s.id} ${s.name} ${name(db, s.ownerId)}`} onOpen={s => nav({ page: 'a-seller', id: s.id })}
      filters={[{ k: 'st', label: 'State', options: ['Draft', 'Email verification pending', 'Verification pending', 'More information required', 'Active', 'Rejected', 'Suspended'].map(x => [x, x]), test: (s, v) => s.status === v }, { k: 'rv', label: 'Reviewer', options: [['none', 'Unassigned'], ...Object.values(db.staff).filter(x => x.roles.includes('verification')).map(x => [x.id, x.name])], test: (s, v) => v === 'none' ? !s.reviewer : s.reviewer === v }]}
      sorts={[{ id: 'sub', label: 'Submitted (oldest)', fn: (a, b) => (a.submitted || 0) - (b.submitted || 0) }, { id: 'name', label: 'Name', fn: (a, b) => a.name.localeCompare(b.name) }]}
      cols={[{ k: 'id', label: 'Seller ID', render: s => <code className="xs">{s.id}</code> }, { k: 'n', label: 'Store', render: s => <b className="small">{s.name}</b> }, { k: 'a', label: 'Account', render: s => db.users[s.ownerId].acct }, { k: 'sub', label: 'Submitted', render: s => s.submitted ? fmtDate(s.submitted) : '—' },
        { k: 'st', label: 'State', render: s => <Badge tone={{ Active: 'ok', Suspended: 'bad', Rejected: 'bad' }[s.status] || 'warn'} dot>{s.status}{s.paused ? ' · paused' : ''}</Badge> }, { k: 'c', label: 'Category', render: s => CATEGORIES.find(c => c.id === s.cat)?.name }, { k: 'r', label: 'Reviewer', render: s => staffName(db, s.reviewer) }, { k: 'o', label: 'Outstanding', render: s => <span className="small">{s.outstanding.join(', ') || '—'}</span> }]} /></>;
}
export function ASeller() {
  const { db, staff, route, nav, act, update, perform } = useApp(); const g = useGate(['s', route.id]); const [dlg, setDlg] = useState(null);
  const st = db.stores[route.id]; const v = db.verifications.find(x => x.storeId === route.id); const [seen, setSeen] = useState(v?.version); useEffect(() => { if (seen == null && v) setSeen(v.version); });
  if (g) return g; if (!st) return <Empty title="Seller not found" />;
  const ls = db.listings.filter(l => l.storeId === st.id); const os = db.orders.filter(o => o.storeId === st.id && o.payment.status === 'Paid');
  const since = now() - 90 * DAY; const inP = os.filter(o => o.placedAt >= since);
  const perf = [['Completed orders', inP.filter(o => o.status === 'completed').length, `of ${inP.length} paid orders in 90 days`], ['Overdue deliveries', inP.filter(isOverdue).length, `of ${inP.length}`], ['Cancellation rate', inP.length ? Math.round(100 * inP.filter(o => o.status === 'cancelled').length / inP.length) + '%' : '—', `${inP.filter(o => o.status === 'cancelled').length} of ${inP.length} orders`], ['Disputes', db.cases.filter(c => c.storeId === st.id && c.openedAt >= since).length, `on ${inP.length} eligible orders`], ['Refund total', fmtMoney(db.refunds.filter(r => r.storeId === st.id && ['Refunded', 'Partially refunded'].includes(r.status)).reduce((a, r) => a + r.amountC, 0)), 'confirmed refunds']];
  const run = async (name, args, fn, msg) => { const r = await perform(name, args, fn, msg); if (!r.ok && r.error.code === 'stale') setSeen(db.verifications.find(x => x.storeId === st.id)?.version); else if (r.ok) setSeen(null); return r; };
  const cur = v ? (seen ?? v.version) : null;
  return <>
    <DetailHead back={{ label: 'Sellers', route: { page: 'a-sellers' } }} refId={st.id} title={st.name} badges={<><Badge tone={{ Active: 'ok', Suspended: 'bad' }[st.status] || 'warn'} dot>{st.status}</Badge>{st.paused && <Badge tone="warn">New sales paused</Badge>}{v && <Badge tone="muted">Verification {v.id} v{v.version}</Badge>}</>}
      actions={<>{v?.state === 'Verification pending' && <><Btn v="primary" disabled={!can(db, staff, 'sellers.decide')} onClick={() => setDlg('approve')}>Approve</Btn><Btn disabled={!can(db, staff, 'sellers.decide')} onClick={() => setDlg('info')}>Request information</Btn><Btn v="ghost" disabled={!can(db, staff, 'sellers.decide')} onClick={() => setDlg('reject')}>Reject</Btn></>}
        {can(db, staff, 'stores.control') && <><Btn size="sm" onClick={() => setDlg('pause')} disabled={st.paused || st.status !== 'Active'}>Pause sales</Btn><Btn size="sm" onClick={() => setDlg('suspend')} disabled={st.status !== 'Active'}>Suspend</Btn><Btn size="sm" onClick={() => setDlg('restore')} disabled={st.status !== 'Suspended' && !st.paused}>Restore</Btn><Btn size="sm" v="ghost" onClick={() => setDlg('corrections')}>Request corrections</Btn></>}</>} />
    {v && seen != null && seen !== v.version && <Notice tone="warn" title="This application changed">Version {v.version} is now shown. Review it before deciding.</Notice>}
    {!apiEnabled && v?.state === 'More information required' && <Notice tone="info" title="Waiting for the seller" action={<Btn size="sm" onClick={() => run(null, null, d => O.sellerResubmit(d, st.id), 'Demo resubmission received')}>Simulate seller resubmission</Btn>}>Requested: {v.missing.join(', ')}. <Sim>Demo control</Sim></Notice>}
    <DetailGrid main={<DTabs tabs={[
      { id: 'ov', label: 'Onboarding', body: v ? <Section><KV items={[['Legal name', v.identity.name], ['Country', v.identity.country], ['Date of birth', can(db, staff, 'sellers.evidence') ? v.identity.dob : 'Hidden (needs evidence permission)'], ['Business', v.business.name], ['Address', v.business.address || <span className="bad-t">Missing</span>], ['Registration', v.business.registration || <span className="bad-t">Missing</span>], ['Submitted', fmtDT(v.submittedAt)]]} />
        {v.kyc && <><h3 className="sub-h">Identity check by {v.kyc.provider}</h3><KV items={[['Result', <Badge tone={v.kyc.status === 'Approved' ? 'ok' : v.kyc.status === 'Declined' ? 'bad' : 'warn'}>{v.kyc.status}</Badge>], ['Updated', fmtDT(v.kyc.at)], ...(v.kyc.result ? [['Verified name', <span>{v.kyc.result.name || '—'}{v.kyc.result.name && v.kyc.result.name.trim().toLowerCase() !== v.identity.name.trim().toLowerCase() && <span className="bad-t"> · differs from the application ({v.identity.name})</span>}</span>], ['Verified date of birth', v.kyc.result.dob || '—'], ['Document', [v.kyc.result.document, v.kyc.result.country].filter(Boolean).join(' · ') || '—'], ['Sanctions screening', v.kyc.result.aml || 'Not part of the check']] : v.kyc.status === 'Approved' || v.kyc.status === 'Declined' ? [['Verified details', 'Hidden (needs evidence permission)']] : [])]} /></>}
        <h3 className="sub-h">{v.kyc ? 'Verification checks' : <>Demo verification checks <Sim>No provider contacted</Sim></>}</h3><div className="checks-grid">{Object.entries(v.checks).map(([k, ok]) => <div key={k} className="row-gap"><Badge tone={ok ? 'ok' : 'warn'}>{ok ? 'Complete' : 'Outstanding'}</Badge><span className="small">{k}</span>{!ok && v.state === 'Verification pending' && !(v.kyc && k === 'identity') && <Btn size="sm" v="ghost" disabled={!can(db, staff, 'sellers.decide')} onClick={() => run('sellerMarkCheck', { storeId: st.id, check: k }, d => O.markCheck(d, staff, st.id, k), 'Check recorded')}>Mark complete</Btn>}</div>)}</div></Section> : <Empty title="No verification submission" /> },
      { id: 'ev', label: 'Evidence', body: <Section><Evidence perm="sellers.evidence" label="Identity and business documents" k={'seller:' + st.id + ':evidence'}>{v?.evidence.length ? v.evidence.map((f, i) => <FileChip key={i} f={f} />) : <p className="muted small">No documents.</p>}<p className="xs muted">Placeholder files only. No real identity documents are stored in this prototype.</p></Evidence></Section> },
      { id: 'hist', label: 'Verification history', count: v?.decisions.length, body: <Section>{v?.decisions.length ? <ol className="timeline">{[...v.decisions].reverse().map((x, i) => <li key={i}><span className="tl-dot" /><div><div className="tl-text"><b>{x.decision}</b> · v{x.version || v.version} · {x.reason}</div>{x.fields && <div className="xs">Fields: {x.fields.join(', ')}</div>}{x.message && <div className="xs muted">Seller message: {x.message}</div>}<div className="xs muted">{x.by} · {fmtDT(x.at)}</div></div></li>)}</ol> : <p className="muted small">No decisions yet.</p>}</Section> },
      ...(can(db, staff, 'payouts.view') ? [{ id: 'pm', label: 'Payout destinations', count: (db.payoutMethods[st.id] || []).length, body: <Section>{(db.payoutMethods[st.id] || []).length ? (db.payoutMethods[st.id] || []).map(m => <div key={m.id} className="restr"><div className="row-gap"><b className="small">{m.label}</b><Badge tone={m.verified ? 'ok' : 'warn'}>{m.verified ? 'Verified' : 'Not verified'}</Badge>{!m.verified && <Btn size="sm" disabled={!can(db, staff, 'payouts.approve')} onClick={() => setDlg({ verify: m })}>Verify destination</Btn>}</div><span className="xs muted">{m.type} · holder {m.holder}{m.verifiedBy ? ` · verified by ${m.verifiedBy} ${fmtDT(m.verifiedAt)}` : ''}</span>{m.address && <div><code className="addr">{m.address}</code> <span className="xs muted">{m.net}</span></div>}</div>) : <p className="muted small">No payout destinations.</p>}
        <p className="xs muted">A destination must be verified before the seller can request a payout to it. For crypto, add the address to the whitelist in NOWPayments first.</p></Section> }] : []),
      { id: 'list', label: 'Listings', count: ls.length, body: <Table rows={ls} onRow={l => can(db, staff, 'catalog.view') && nav({ page: 'a-product', id: l.id })} cols={[{ k: 't', label: 'Listing', render: l => <span className="small">{l.title}</span> }, { k: 'a', label: 'State', render: l => <Badge tone="muted">{l.availability}</Badge> }, { k: 'p', label: 'From', cls: 'num', render: l => money(startPrice(l)) }]} /> },
      { id: 'perf', label: 'Performance', body: <Section><p className="xs muted">Last 90 days. Each figure states its denominator.</p><div className="perf">{perf.map(([k, v2, d]) => <div key={k}><span className="xs muted">{k}</span><b>{v2}</b><span className="xs">{d}</span></div>)}</div>
        {can(db, staff, 'orders.view') && <Table rows={os} onRow={o => nav({ page: 'a-order', id: o.id })} cols={[{ k: 'id', label: 'Order', render: o => o.id }, { k: 's', label: 'Status', render: o => STATUS_LABEL[o.status] }, { k: 'd', label: 'Case', render: o => o.caseId || '—' }]} />}</Section> },
      { id: 'tl', label: 'Timeline', body: <Section><AuditTrail objects={[st.id]} /></Section> },
    ]} />} side={<><Section title="Store preview"><div className="row-gap"><Avatar name={st.name} hue={st.hue} size={40} square /><div><b className="small">{st.name}</b><span className="xs muted block">{st.tagline}</span></div></div>{st.suspension && <Notice tone="bad" title="Suspended">{st.suspension.reason}</Notice>}</Section>
      {can(db, staff, 'payouts.view') && <Section title="Balance"><KV items={Object.entries(storeBuckets(db, st.id)).filter(([k]) => ['pending', 'held', 'available', 'reserved'].includes(k)).map(([k, c]) => [k, fmtMoney(c)])} /><p className="xs muted">A payout hold needs separate financial authority; store actions do not freeze balances.</p></Section>}
      <SidePanel k={key('seller', st.id)} label={st.id} eligiblePerm="sellers.decide" /></>} />
    {dlg?.verify && <ReasonDialog title="Verify payout destination" intro={`${dlg.verify.label}${dlg.verify.address ? ' · ' + dlg.verify.address : ''}. Confirm it belongs to this seller. For a crypto address, whitelist it in NOWPayments before verifying.`} confirm="Verify destination" onClose={() => setDlg(null)} onSubmit={x => perform('verifyPayoutMethod', { storeId: st.id, methodId: dlg.verify.id, reason: x.reason }, d => verifyPayoutMethod(d, d.staff[staff.id], st.id, dlg.verify.id, x.reason), 'Destination verified')} />}
    {dlg === 'approve' && <ReasonDialog title={`Approve ${st.name}`} intro="Requires every demo check complete. Activates seller eligibility and notifies the seller." confirm="Approve seller" fields={[{ k: 'message', label: 'Message to seller', type: 'textarea', required: true, initial: 'Your store is verified. You can publish listings.' }]} onClose={() => setDlg(null)} onSubmit={x => run('sellerApprove', { storeId: st.id, reason: x.reason, message: x.message, version: cur }, d => O.sellerApprove(d, staff, st.id, x.reason, x.message, cur), 'Seller approved')} />}
    {dlg === 'info' && <InfoDialog onClose={() => setDlg(null)} onSubmit={(fields, msg, reason) => run('sellerRequestInfo', { storeId: st.id, fields, message: msg, reason, version: cur }, d => O.sellerRequestInfo(d, staff, st.id, fields, msg, reason, cur), 'Information requested')} />}
    {dlg === 'reject' && <ReasonDialog title={`Reject ${st.name}`} danger confirm="Reject application" fields={[{ k: 'message', label: 'Message to seller', type: 'textarea', required: true }, { k: 'resub', label: 'Resubmission', type: 'select', options: [['yes', 'Allowed'], ['no', 'Not permitted']], initial: 'yes' }]} onClose={() => setDlg(null)} onSubmit={x => run('sellerReject', { storeId: st.id, reason: x.reason, message: x.message, resubmitAllowed: x.resub === 'yes', version: cur }, d => O.sellerReject(d, staff, st.id, x.reason, x.message, x.resub === 'yes', cur), 'Application rejected')} />}
    {['pause', 'suspend', 'restore', 'corrections'].includes(dlg) && <ReasonDialog title={{ pause: 'Pause new sales', suspend: 'Suspend store', restore: 'Restore store', corrections: 'Request store corrections' }[dlg]} intro="Existing paid orders remain visible for fulfilment and resolution. Balances are not frozen by this action." danger={dlg === 'suspend'} confirm="Apply" fields={[{ k: 'message', label: 'Message to seller', type: 'textarea', required: true }, ...(dlg === 'pause' || dlg === 'suspend' ? [{ k: 'days', label: 'Duration in days (optional)', type: 'number' }] : [])]} onClose={() => setDlg(null)} onSubmit={x => perform('storeControl', { storeId: st.id, action: dlg, reason: x.reason, message: x.message, days: +x.days || 0 }, d => O.storeControl(d, staff, st.id, dlg, x.reason, x.message, +x.days || 0), 'Store updated')} />}
  </>;
}
function InfoDialog({ onClose, onSubmit }) {
  const opts = ['Legal name', 'Date of birth', 'Identity document', 'Business address', 'Company registration number', 'Proof of address', 'Store category'];
  const { withInline } = useApp();
  const [sel, setSel] = useState([]); const [msg, setMsg] = useState(''); const [reason, setReason] = useState(''); const [err, setErr] = useState('');
  return <Modal title="Request information" onClose={onClose} footer={<><Btn v="ghost" onClick={onClose}>Cancel</Btn><Btn v="primary" onClick={async () => { if (!sel.length) return setErr('Select the exact fields.'); if (!msg.trim() || !reason.trim()) return setErr('Enter a seller message and a reason.'); const r = await withInline(() => onSubmit(sel, msg, reason)); if (r.ok) onClose(); else setErr(r.error.message); }}>Return to seller</Btn></>}>
    <fieldset className="types"><legend>Missing or inconsistent fields</legend>{opts.map(o => <label key={o} className="radio"><input type="checkbox" checked={sel.includes(o)} onChange={e => setSel(e.target.checked ? [...sel, o] : sel.filter(x => x !== o))} />{o}</label>)}</fieldset>
    <Field label="Message to seller" required><textarea rows="3" value={msg} onChange={e => setMsg(e.target.value)} /></Field><Field label="Reason (audit)" required><textarea rows="2" value={reason} onChange={e => setReason(e.target.value)} /></Field>{err && <p className="ferr">{err}</p>}</Modal>;
}

// ---------- products and categories
export function AProducts() {
  const { db, nav } = useApp(); const g = useGate(['p']); if (g) return g;
  const rows = db.listings.map(l => ({ ...l, store: db.stores[l.storeId].name, reportsN: db.reports.filter(r => r.listingId === l.id).length }));
  return <><PageTitle title="Products" sub="Listing review and moderation. Decisions notify the seller and never rewrite purchased orders." />
    <AList id="products" rows={rows} search={l => `${l.id} ${l.title} ${l.store}`} onOpen={l => nav({ page: 'a-product', id: l.id })}
      filters={[{ k: 'a', label: 'State', options: ['Draft', 'Pending review', 'Changes requested', 'Active', 'Paused', 'Rejected', 'Archived'].map(x => [x, x]), test: (l, v) => l.availability === v }, { k: 'c', label: 'Category', options: CATEGORIES.map(c => [c.id, c.name]), test: (l, v) => l.cat === v }, { k: 'r', label: 'Reports', options: [['y', 'Has reports']], test: l => l.reportsN > 0 }]}
      sorts={[{ id: 'sub', label: 'Submitted (oldest)', fn: (a, b) => a.submittedAt - b.submittedAt }, { id: 'new', label: 'Newest', fn: (a, b) => b.submittedAt - a.submittedAt }]}
      cols={[{ k: 'id', label: 'Listing ID', render: l => <code className="xs">{l.id}</code> }, { k: 't', label: 'Name', render: l => <span className="trunc2 small">{l.title}</span> }, { k: 's', label: 'Store', render: l => l.store }, { k: 'c', label: 'Category', render: l => SUBS[l.sub]?.name }, { k: 'p', label: 'Price range', render: l => `${money(startPrice(l))} – ${money(Math.max(...l.packages.map(p => p.price)))}` }, { k: 'a', label: 'State', render: l => <Badge tone={{ Active: 'ok', 'Pending review': 'accent', 'Changes requested': 'warn', Rejected: 'bad' }[l.availability] || 'muted'}>{l.availability}</Badge> }, { k: 'd', label: 'Submitted', render: l => fmtDate(l.submittedAt) }, { k: 'r', label: 'Reports', cls: 'num', render: l => l.reportsN }]} /></>;
}
export function AProduct() {
  const { db, staff, route, nav, act, perform } = useApp(); const g = useGate(['p', route.id]); const [dlg, setDlg] = useState(null); if (g) return g;
  const l = db.listings.find(x => x.id === route.id); if (!l) return <Empty title="Listing not found" />;
  const st = db.stores[l.storeId]; const reps = db.reports.filter(r => r.listingId === l.id); const ords = db.orders.filter(o => o.snap.listingId === l.id);
  const mod = can(db, staff, 'catalog.moderate'); const A = { approve: ['Pending review'], changes: ['Pending review', 'Active', 'Paused'], reject: ['Pending review', 'Changes requested'], pause: ['Active'], restore: ['Paused'], archive: ['Active', 'Paused', 'Rejected', 'Changes requested', 'Draft'] };
  const label = { approve: 'Approve publication', changes: 'Request changes', reject: 'Reject', pause: 'Pause', restore: 'Restore', archive: 'Archive' };
  return <>
    <DetailHead back={{ label: 'Products', route: { page: 'a-products' } }} refId={l.id} title={l.title} badges={<><Badge tone={{ Active: 'ok', 'Pending review': 'accent', 'Changes requested': 'warn', Rejected: 'bad' }[l.availability] || 'muted'}>{l.availability}</Badge><Badge tone="muted">{st.name} · {st.status}</Badge><Badge tone="muted">Version {(l.versions || []).length}</Badge></>}
      amounts={[['From', money(startPrice(l))], ['Packages', l.packages.length]]} actions={mod ? Object.keys(A).map(a => <Btn key={a} size="sm" v={a === 'approve' ? 'primary' : a === 'reject' || a === 'archive' ? 'ghost' : 'secondary'} disabled={!A[a].includes(l.availability)} onClick={() => setDlg(a)}>{label[a]}</Btn>) : <span className="xs muted">Your role can view but not moderate listings.</span>} />
    {l.reviewNote && <Notice tone="warn" title="Review note">{l.reviewNote}</Notice>}
    <DetailGrid main={<DTabs tabs={[
      { id: 'ov', label: 'Proposed listing', body: <Section><div className="row-gap"><ProductArt sub={l.sub} art={l.art} size="thumb" /><div><b>{l.title}</b><span className="xs muted block">{SUBS[l.sub]?.catName} › {SUBS[l.sub]?.name}</span></div></div><p className="small">{l.description}</p>
        <KV items={[['Delivery', `${l.deliveryMethod}, ${l.deliveryDays} days`], ['Replacement terms', l.replacement], ['Buyer requirements', l.requirements || '—'], ['Usage', l.usage]]} />
        <Table rows={l.packages} cols={[{ k: 'n', label: 'Package', render: p => <b className="small">{p.name}</b> }, { k: 'd', label: 'Description', render: p => <span className="small">{p.desc}</span> }, { k: 'q', label: 'Quantity', cls: 'num', render: p => `${fmtN(p.qty)} ${l.unit}` }, { k: 'p', label: 'Price', cls: 'num', render: p => money(p.price) }, { k: 't', label: 'Delivery', render: p => p.days + ' d' }]} /></Section> },
      { id: 'ver', label: 'Versions', count: (l.versions || []).length, body: <Section>{(l.versions || []).slice().reverse().map(v => <div key={v.v} className="restr"><b className="small">Version {v.v}</b> <span className="xs muted">{fmtDT(v.at)} · {v.by}</span><p className="xs">{v.packages.map(p => `${p.name} ${money(p.price)}`).join(' · ')}</p><p className="xs muted">Replacement: {v.replacement}</p></div>)}</Section> },
      { id: 'rep', label: 'Reports', count: reps.length, body: <Section>{reps.length ? reps.map(r => <div key={r.id} className="restr"><div className="row-gap"><b className="small">{r.id}</b><Badge tone={r.status === 'Open' ? 'warn' : 'muted'}>{r.status}</Badge><span className="xs muted">{fmtDT(r.at)}</span></div><p className="small">{r.reason}</p>{r.evidence && <span className="xs muted">Evidence: {r.evidence}</span>}{r.status === 'Open' && mod && <div className="row-gap"><Btn size="sm" onClick={() => setDlg({ report: r, outcome: 'Action taken' })}>Action taken</Btn><Btn size="sm" v="ghost" onClick={() => setDlg({ report: r, outcome: 'No violation found' })}>No violation</Btn></div>}</div>) : <p className="muted small">No reports.</p>}</Section> },
      { id: 'ord', label: 'Orders', count: ords.length, body: <Section><p className="xs muted">Orders keep the version they bought. Moderation does not change these snapshots.</p><Table rows={ords} cols={[{ k: 'id', label: 'Order', render: o => o.id }, { k: 'v', label: 'Version bought', render: o => 'v' + (o.snap.listingVersion || 1) }, { k: 'p', label: 'Package', render: o => `${o.snap.pkgName} ${money(o.snap.price)}` }]} /></Section> },
      { id: 'tl', label: 'Timeline', body: <Section><AuditTrail objects={[l.id]} /></Section> },
    ]} />} side={<SidePanel k={key('listing', l.id)} label={l.id} eligiblePerm="catalog.moderate" />} />
    {typeof dlg === 'string' && <ReasonDialog title={label[dlg]} intro="The seller is notified. Staff request corrections rather than silently changing commercial terms." confirm={label[dlg]} danger={dlg === 'reject' || dlg === 'archive'} fields={[{ k: 'message', label: 'Message to seller', type: 'textarea', required: dlg !== 'approve', initial: dlg === 'changes' && l.reviewNote ? l.reviewNote : '' }]} onClose={() => setDlg(null)} onSubmit={v => perform('moderateListing', { listingId: l.id, action: dlg, reason: v.reason, message: v.message || 'Approved for publication.' }, d => O.moderateListing(d, staff, l.id, dlg, v.reason, v.message || 'Approved for publication.'), 'Listing updated')} />}
    {dlg?.report && <ReasonDialog title={`Review ${dlg.report.id}: ${dlg.outcome}`} confirm="Record outcome" onClose={() => setDlg(null)} onSubmit={v => perform('resolveReport', { reportId: dlg.report.id, outcome: dlg.outcome, reason: v.reason }, d => O.resolveReport(d, staff, dlg.report.id, dlg.outcome, v.reason), 'Report reviewed')} />}
  </>;
}

export function ACategories() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['cat']); const [dlg, setDlg] = useState(null); if (g) return g;
  const editable = can(db, staff, 'categories.edit');
  const count = (cid, sid) => db.listings.filter(l => (sid ? l.sub === sid : l.cat === cid) && l.availability !== 'Archived').length;
  return <><PageTitle title="Categories" sub="Display names, order and availability. Disabling a populated category needs a decision about its listings." />
    {!editable && <Notice tone="info">Your role can view categories but not change them.</Notice>}
    {db.categories.slice().sort((a, b) => a.order - b.order).map(c => <Section key={c.id} title={<span className="row-gap">{c.name}<Badge tone={c.active ? 'ok' : 'muted'}>{c.active ? 'Active' : 'Disabled'}</Badge><code className="xs">{c.id}</code></span>} action={editable && <div className="row-gap"><Btn size="sm" onClick={() => setDlg({ c, rename: true })}>Rename</Btn><Btn size="sm" onClick={() => setDlg({ c, toggle: true })}>{c.active ? 'Disable' : 'Enable'}</Btn><Btn size="sm" v="ghost" onClick={() => setDlg({ c, add: true })}>Add subcategory</Btn></div>}>
      <Table rows={c.subs.slice().sort((a, b) => a.order - b.order)} cols={[{ k: 'n', label: 'Subcategory', render: s => <b className="small">{s.name}</b> }, { k: 'slug', label: 'Slug', render: s => <code className="xs">{s.id}</code> }, { k: 'o', label: 'Order', cls: 'num', render: s => s.order + 1 }, { k: 'n2', label: 'Listings', cls: 'num', render: s => count(c.id, s.id) }, { k: 'a', label: 'State', render: s => <Badge tone={s.active ? 'ok' : 'muted'}>{s.active ? 'Active' : 'Disabled'}</Badge> },
        { k: 'x', label: '', render: s => editable && <div className="row-acts"><Btn size="sm" v="ghost" onClick={() => setDlg({ c, s, rename: true })}>Rename</Btn><Btn size="sm" v="ghost" onClick={() => setDlg({ c, s, toggle: true })}>{s.active ? 'Disable' : 'Enable'}</Btn><Btn size="sm" v="ghost" disabled={s.order === 0} onClick={() => perform('reorderSubcategory', { categoryId: c.id, subId: s.id }, d => O.reorderSubcategory(d, staff, c.id, s.id))}>Move up</Btn></div> }]} /></Section>)}
    {dlg?.rename && <ReasonDialog title={`Rename ${(dlg.s || dlg.c).name}`} confirm="Save name" fields={[{ k: 'name', label: 'Display name', required: true, initial: (dlg.s || dlg.c).name }]} onClose={() => setDlg(null)} onSubmit={v => perform('editCategory', { categoryId: dlg.c.id, subId: dlg.s?.id, name: v.name.trim(), reason: v.reason }, d => O.editCategory(d, staff, dlg.c.id, dlg.s?.id, { name: v.name.trim() }, v.reason), 'Category renamed')} />}
    {dlg?.add && <ReasonDialog title={`Add subcategory to ${dlg.c.name}`} confirm="Add" fields={[{ k: 'name', label: 'Name', required: true }]} onClose={() => setDlg(null)} onSubmit={v => perform('addSubcategory', { categoryId: dlg.c.id, name: v.name, reason: v.reason }, d => O.addSubcategory(d, staff, dlg.c.id, v.name, v.reason), 'Subcategory added')} />}
    {dlg?.toggle && (() => { const t = dlg.s || dlg.c; const n = count(dlg.c.id, dlg.s?.id); const disabling = t.active; const others = Object.values(SUBS).filter(x => x.id !== dlg.s?.id && x.cat !== (dlg.s ? '' : dlg.c.id) && x.active);
      return <ReasonDialog title={`${disabling ? 'Disable' : 'Enable'} ${t.name}`} intro={disabling && n ? `${n} listings use this category. Choose what happens to them.` : disabling ? 'No listings are affected.' : 'Listings in this category become visible again if they are active.'} confirm={disabling ? 'Disable' : 'Enable'} danger={disabling}
        fields={disabling && n ? [{ k: 'decision', label: 'Affected listings', type: 'select', options: [['pause', 'Pause them (sellers notified)'], ...others.map(o => ['move:' + o.id, 'Move to ' + o.catName + ' › ' + o.name])], initial: 'pause' }] : []}
        onClose={() => setDlg(null)} onSubmit={v => perform('editCategory', { categoryId: dlg.c.id, subId: dlg.s?.id, active: !disabling, reason: v.reason, decision: v.decision ? (v.decision === 'pause' ? { type: 'pause' } : { type: 'move', to: v.decision.slice(5) }) : null }, d => O.editCategory(d, staff, dlg.c.id, dlg.s?.id, { active: !disabling }, v.reason, v.decision ? (v.decision === 'pause' ? { type: 'pause' } : { type: 'move', to: v.decision.slice(5) }) : null), 'Category updated')} />; })()}
  </>;
}

export function AContent() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['ct']); const [edit, setEdit] = useState(null); const [dlg, setDlg] = useState(null); const [pol, setPol] = useState(null); const [vw, setVw] = useState('desktop'); if (g) return g;
  const pub = can(db, staff, 'content.publish');
  return <><PageTitle title="Content" sub="Homepage banners, featured products, FAQs, announcements and policy drafts. Publishing policies needs Super Admin." />
    <Section title="Homepage banners" action={<Btn size="sm" icon="plus" onClick={() => setEdit({ title: '', sub: '', link: '', order: db.content.banners.length + 1, start: now(), end: now() + 14 * DAY, hue: 200 })}>New banner</Btn>}>
      <Table rows={db.content.banners} cols={[{ k: 't', label: 'Title', render: b => <b className="small">{b.title}</b> }, { k: 'l', label: 'Link', render: b => b.link ? <code className="xs">{b.link}</code> : <span className="bad-t xs">Missing</span> }, { k: 'o', label: 'Order', cls: 'num', render: b => b.order }, { k: 'd', label: 'Active dates', render: b => <span className="xs">{fmtDate(b.start)} – {fmtDate(b.end)}</span> }, { k: 's', label: 'State', render: b => <Badge tone={b.state === 'Active' ? 'ok' : 'muted'}>{b.state}</Badge> },
        { k: 'x', label: '', render: b => <div className="row-acts"><Btn size="sm" v="ghost" onClick={() => setEdit(b)}>Edit</Btn>{b.state !== 'Active' && <Btn size="sm" disabled={!pub} title={pub ? '' : 'Needs content publish permission'} onClick={() => setDlg({ publish: b })}>Publish</Btn>}{b.state === 'Active' && <Btn size="sm" v="ghost" disabled={!pub} onClick={() => setDlg({ archive: b })}>Archive</Btn>}</div> }]} />
      <div className="row-between"><span className="small">Preview</span><Seg label="Preview size" value={vw} onChange={setVw} options={[{ id: 'desktop', label: 'Desktop' }, { id: 'mobile', label: 'Mobile' }]} /></div>
      <div className={'banner-preview ' + vw}>{db.content.banners.filter(b => b.state === 'Active').sort((a, b) => a.order - b.order).map(b => <div key={b.id} className="banner-pv" style={{ '--h': b.hue }}><b>{b.title}</b><span className="small">{b.sub}</span></div>)}{!db.content.banners.some(b => b.state === 'Active') && <p className="muted small">No active banners.</p>}</div>
    </Section>
    <Section title="Featured products"><div className="chips-row">{db.content.featured.map(id => { const l = db.listings.find(x => x.id === id); return <span key={id} className="chip on">{l?.title.slice(0, 32)}<button aria-label="Remove" onClick={() => perform('setFeatured', { listingId: id, on: false }, d => O.setFeatured(d, staff, id, false), 'Removed')}><Icon n="x" s={12} /></button></span>; })}
      <select aria-label="Add featured product" value="" onChange={e => e.target.value && perform('setFeatured', { listingId: e.target.value, on: true }, d => O.setFeatured(d, staff, e.target.value, true), 'Added')}><option value="">Add product…</option>{db.listings.filter(l => l.availability === 'Active' && !db.content.featured.includes(l.id)).map(l => <option key={l.id} value={l.id}>{l.title.slice(0, 50)}</option>)}</select></div></Section>
    <Section title="FAQs"><ul className="faq-admin">{db.content.faqs.map(([q, a], i) => <li key={i}><b className="small">{q}</b><p className="xs muted">{a}</p></li>)}</ul></Section>
    <Section title="Policies (drafts)"><p className="xs muted">Content editors draft and submit. Publication needs the Super Admin policy permission, and orders keep the version accepted at checkout.</p>
      <Table rows={db.policies} cols={[{ k: 't', label: 'Policy', render: p => <b className="small">{p.title}</b> }, { k: 'p', label: 'Published', render: p => 'v' + (p.versions.find(v => v.state === 'Published')?.v || '—') }, { k: 'd', label: 'Draft', render: p => { const d = p.versions.find(v => ['Draft', 'In review'].includes(v.state)); return d ? `v${d.v} · ${d.state}` : '—'; } },
        { k: 'x', label: '', render: p => <div className="row-acts"><Btn size="sm" onClick={() => setPol(p)}>Edit draft</Btn>{p.versions.some(v => v.state === 'Draft') && <Btn size="sm" v="ghost" onClick={() => perform('submitPolicy', { policyId: p.id }, d => O.submitPolicy(d, staff, p.id), 'Submitted for review')}>Submit for review</Btn>}</div> }]} /></Section>
    {edit && <BannerEditor b={edit} onClose={() => setEdit(null)} />}
    {dlg?.publish && <ReasonDialog title={`Publish ${dlg.publish.title}`} intro="Updates the website preview and creates an audit event." confirm="Publish" onClose={() => setDlg(null)} onSubmit={v => perform('publishBanner', { bannerId: dlg.publish.id, reason: v.reason }, d => O.publishBanner(d, staff, dlg.publish.id, v.reason), 'Banner published')} />}
    {dlg?.archive && <ReasonDialog title={`Archive ${dlg.archive.title}`} confirm="Archive" onClose={() => setDlg(null)} onSubmit={v => perform('archiveBanner', { bannerId: dlg.archive.id, reason: v.reason }, d => O.archiveBanner(d, staff, dlg.archive.id, v.reason), 'Banner archived')} />}
    {pol && <ReasonDialog title={`Draft: ${pol.title}`} intro="Placeholder text only. Final legal wording is a separate approved deliverable." confirm="Save draft" fields={[{ k: 'content', label: 'Draft text', type: 'textarea', required: true, initial: (pol.versions.find(v => ['Draft', 'In review'].includes(v.state)) || pol.versions[pol.versions.length - 1]).content }]} onClose={() => setPol(null)} onSubmit={v => perform('draftPolicy', { policyId: pol.id, content: v.content, reason: v.reason }, d => O.draftPolicy(d, staff, pol.id, v.content, v.reason), 'Draft saved')} />}
  </>;
}
function BannerEditor({ b, onClose }) {
  const { staff, act, perform } = useApp(); const toDate = t => new Date(t).toISOString().slice(0, 10);
  return <ReasonDialog title={b.id ? `Edit ${b.id}` : 'New banner'} confirm="Save draft" fields={[{ k: 'title', label: 'Title', required: true, initial: b.title }, { k: 'sub', label: 'Supporting text', initial: b.sub }, { k: 'link', label: 'Destination link', hint: 'search:data, product:l_vps, store:st_atlas, page:help or https://…', initial: b.link }, { k: 'order', label: 'Display order', type: 'number', initial: b.order }, { k: 'start', label: 'Start date', type: 'date', initial: toDate(b.start) }, { k: 'end', label: 'End date', type: 'date', initial: toDate(b.end) }]}
    onClose={onClose} onSubmit={v => perform('saveBanner', { banner: { ...b, title: v.title, sub: v.sub, link: v.link.trim(), order: +v.order, start: new Date(v.start).getTime(), end: new Date(v.end).getTime() }, reason: v.reason }, d => O.saveBanner(d, staff, { ...b, title: v.title, sub: v.sub, link: v.link.trim(), order: +v.order, start: new Date(v.start).getTime(), end: new Date(v.end).getTime() }, v.reason), 'Banner draft saved')} />;
}

// ---------- orders
export function AOrders() {
  const { db, staff, nav } = useApp(); const g = useGate(['o']); if (g) return g;
  const rows = db.orders.map(o => ({ ...o, buyer: name(db, o.buyerId), seller: o.snap.storeName, inv: assignment(db, key('order', o.id)).assigneeId, caseOpen: !!openCase(db, o) }));
  return <><PageTitle title="Orders" sub="Payment, fulfilment, dispute and refund states are tracked separately." actions={<ExportButton name="Orders" rows={rows} cols={[['Order', r => r.id], ['Purchase group', r => r.purchaseRef], ['Seller', r => r.seller], ['Amount USD', r => r.total.toFixed(2)], ['Payment', r => r.payment.status], ['Fulfilment', r => STATUS_LABEL[r.status]]]} />} />
    <AList id="orders" rows={rows} search={o => `${o.id} ${o.purchaseRef} ${o.buyer} ${o.seller} ${o.snap.title}`} onOpen={o => nav({ page: 'a-order', id: o.id })}
      filters={[{ k: 'f', label: 'Fulfilment', options: Object.entries(STATUS_LABEL), test: (o, v) => o.status === v }, { k: 'p', label: 'Payment', options: ['Paid', 'Failed', 'Expired'].map(x => [x, x]), test: (o, v) => o.payment.status === v }, { k: 'x', label: 'Flags', options: [['overdue', 'Overdue'], ['case', 'Open case'], ['refund', 'Has refund']], test: (o, v) => v === 'overdue' ? isOverdue(o) : v === 'case' ? o.caseOpen : !!o.refund }]}
      sorts={[{ id: 'new', label: 'Newest', fn: (a, b) => b.placedAt - a.placedAt }, { id: 'due', label: 'Deadline', fn: (a, b) => a.dueAt - b.dueAt }]}
      cols={[{ k: 'id', label: 'Order', render: o => <><b>{o.id}</b><span className="xs muted block">{o.purchaseRef}</span></> }, { k: 'b', label: 'Buyer / seller', render: o => <span className="small">{o.buyer}<br />{o.seller}</span> }, { k: 'p', label: 'Product', render: o => <span className="trunc2 small">{o.snap.title}</span> }, { k: 'q', label: 'Qty', cls: 'num', render: o => fmtN(o.totalQty) },
        { k: 'a', label: 'Amount', cls: 'num', render: o => money(o.total) }, { k: 'st', label: 'States', render: o => <div className="badges"><Badge tone={PAY_T[o.payment.status]}>Payment {o.payment.status}</Badge><Badge tone={STATUS_TONE[o.status]}>{STATUS_LABEL[o.status]}</Badge>{o.caseOpen && <Badge tone="warn">Case open</Badge>}{o.refund && <Badge tone="info">Refund {o.refund.state}</Badge>}{isOverdue(o) && <Badge tone="bad">Overdue</Badge>}</div> },
        { k: 'd', label: 'Deadline', render: o => ['completed', 'cancelled', 'refunded', 'unpaid'].includes(o.status) ? '—' : fmtDate(o.dueAt) }, { k: 'i', label: 'Investigator', render: o => <span className="small">{staffName(db, o.inv)}</span> }]} /></>;
}
export function AOrder() {
  const { db, staff, route, nav, act, perform } = useApp(); const g = useGate(['o', route.id]); const [dlg, setDlg] = useState(null); if (g) return g;
  const o = db.orders.find(x => x.id === route.id); if (!o) return <Empty title="Order not found" />;
  const p = db.purchases.find(x => x.id === o.purchaseRef); const siblings = p ? p.orderIds.map(id => db.orders.find(x => x.id === id)).filter(Boolean) : [o];
  const pay = db.payments.find(x => x.purchaseId === o.purchaseRef); const refunds = db.refunds.filter(r => r.orderId === o.id); const kase = o.caseId && db.cases.find(c => c.id === o.caseId);
  const ob = orderBuckets(db, o.id); const entries = db.ledger.filter(e => e.order === o.id).concat(db.platform.filter(e => e.order === o.id).map(e => ({ ...e, platform: true })));
  const conv = db.conversations.find(c => c.buyerId === o.buyerId && c.storeId === o.storeId);
  const why = isOverdue(o) ? `Overdue: deadline ${fmtDT(o.dueAt)} passed ${rel(o.dueAt)} while ${STATUS_LABEL[o.status].toLowerCase()}.` : o.status === 'awaiting_info' ? `Waiting for buyer information: ${o.infoRequest?.text}` : o.status === 'partial' ? `Partially delivered: ${fmtN(deliveredQty(o))} of ${fmtN(o.totalQty)} ${o.snap.unit}.` : o.status === 'delivered' ? 'Delivered and awaiting buyer confirmation. Staff cannot confirm on the buyer’s behalf.' : o.status === 'unpaid' ? `No verified payment (${o.payment.status}). Not in paid sales or earnings.` : null;
  const actOk = can(db, staff, 'orders.act');
  return <>
    <DetailHead back={{ label: 'Orders', route: { page: 'a-orders' } }} refId={o.purchaseRef} title={o.id} badges={<><Badge tone={PAY_T[o.payment.status]}>Payment: {o.payment.status}</Badge><Badge tone={STATUS_TONE[o.status]}>Fulfilment: {STATUS_LABEL[o.status]}</Badge><Badge tone={kase ? CASE_T[kase.status] : 'muted'}>Dispute: {kase ? kase.status : 'None'}</Badge><Badge tone={o.refund ? 'info' : 'muted'}>Refund: {o.refund ? o.refund.state : 'None'}</Badge>{isOverdue(o) && <Badge tone="bad">Overdue</Badge>}</>}
      amounts={[['Order amount', money(o.total)], ['Refunded', fmtMoney(refundedC(db, o))], ['Refundable', fmtMoney(refundableC(db, o))]]}
      actions={<>{actOk && <><Btn size="sm" disabled={!['paid', 'preparing', 'awaiting_info'].includes(o.status)} onClick={() => setDlg('info')}>Request buyer information</Btn><Btn size="sm" onClick={() => setDlg('contact')}>Contact party</Btn><Btn size="sm" disabled={!['paid', 'preparing', 'partial', 'awaiting_info'].includes(o.status)} onClick={() => setDlg('ext')}>Record agreed extension</Btn><Btn size="sm" v="ghost" disabled={['delivered', 'completed', 'cancelled', 'refunded'].includes(o.status)} onClick={() => setDlg('cancel')}>Cancel order</Btn></>}
        <Btn size="sm" v="ghost" onClick={() => setDlg('esc')}>Escalate</Btn>{can(db, staff, 'refunds.request') && o.payment.status === 'Paid' && <Btn size="sm" onClick={() => nav({ page: 'a-refunds', newFor: o.id })}>Request refund</Btn>}{kase && <Btn size="sm" onClick={() => nav({ page: 'a-case', id: kase.id })}>Open case</Btn>}</>} />
    {why && <Notice tone={isOverdue(o) ? 'bad' : 'info'}>{why}</Notice>}
    <DetailGrid main={<DTabs tabs={[
      { id: 'ov', label: 'Overview', body: <><Section title="Purchased snapshot (immutable)"><KV items={[['Listing', `${o.snap.title} (version ${o.snap.listingVersion || 1})`], ['Package', `${o.snap.pkgName}: ${o.snap.pkgDesc}`], ['Quantity', `${o.count} × ${fmtN(o.snap.qty)} = ${fmtN(o.totalQty)} ${o.snap.unit}`], ['Price', money(o.snap.price)], ['Delivery', `${o.snap.deliveryMethod}, ${o.snap.days} days`], ['Replacement', o.snap.replacement], ['Commission', `${o.commissionRate * 100}% (${o.commissionRule}), fixed at purchase`], ['Terms accepted', o.termsVersion], ['Buyer requirements', o.requirements || '—']]} /></Section>
        <Section title={`Purchase group ${o.purchaseRef}`}><Table rows={siblings} cols={[{ k: 'id', label: 'Order', render: x => <b className={x.id === o.id ? '' : 'muted'}>{x.id}</b> }, { k: 's', label: 'Seller', render: x => x.snap.storeName }, { k: 'a', label: 'Allocation', cls: 'num', render: x => money(x.total) }]} /><p className="small">Charged once: <b>{p ? money(p.total) : money(o.total)}</b> via {pay?.method || o.payment.method} ({pay?.id || '—'}). Each order shows only its allocation.</p></Section></> },
      { id: 'del', label: 'Deliveries', count: o.deliveries.length, body: <Section><p className="small">{o.deliveries.length} version(s). Delivered {fmtN(deliveredQty(o))} of {fmtN(o.totalQty)}.</p>{o.deliveries.map(dl => <div key={dl.v} className="restr"><b className="small">Version {dl.v} · {dl.kind}</b> <span className="xs muted">{fmtDT(dl.at)} · qty {fmtN(dl.qty)}</span><p className="xs">{dl.note}</p></div>)}
        <Evidence perm="orders.evidence" label="Delivery files" k={'order:' + o.id + ':files'}>{o.deliveries.map(dl => dl.file && <FileChip key={dl.v} f={dl.file} locked />)}{!o.deliveries.length && <p className="muted small">No files.</p>}</Evidence></Section> },
      { id: 'msg', label: 'Messages', body: <Section><Evidence perm="orders.evidence" label="Buyer and seller messages" k={'order:' + o.id + ':messages'}>{conv ? conv.messages.slice(-8).map(m => <div key={m.id} className="pv-row"><b className="xs">{m.from}</b><span className="small">{m.text}</span><span className="xs muted">{fmtDT(m.at)}</span></div>) : <p className="muted small">No conversation.</p>}</Evidence></Section> },
      { id: 'money', label: 'Money', body: <Section><KV items={[['Seller pending', fmtMoney(ob.pending)], ['On dispute hold', fmtMoney(ob.held)], ['Released', fmtMoney(ob.available)], ['Reversed by refunds', fmtMoney(ob.refunded)]]} />
        <Table rows={entries.sort((a, b) => a.at - b.at)} cols={[{ k: 'id', label: 'Entry', render: e => <code className="xs">{e.id}</code> }, { k: 'k', label: 'Type', render: e => e.kind + (e.platform ? ' (platform)' : '') }, { k: 'm', label: 'Movement', render: e => e.from ? `${e.from === 'ext' ? 'new' : e.from} → ${e.to}` : '—' }, { k: 'a', label: 'Amount', cls: 'num', render: e => <M c={e.amt} /> }]} />
        {refunds.length > 0 && <Table rows={refunds} onRow={r => nav({ page: 'a-refund', id: r.id })} cols={[{ k: 'id', label: 'Refund', render: r => r.id }, { k: 'a', label: 'Amount', cls: 'num', render: r => <M c={r.amountC} /> }, { k: 's', label: 'Status', render: r => r.status }]} />}</Section> },
      { id: 'tl', label: 'Timeline', body: <Section><Timeline events={o.events} /><h3 className="sub-h">Administrative actions</h3><AuditTrail objects={[o.id]} /></Section> },
    ]} />} side={<><Section title="Parties"><KV items={[['Buyer', name(db, o.buyerId) + ' · ' + db.users[o.buyerId].acct], ['Seller', o.snap.storeName], ['Placed', fmtDT(o.placedAt)], ['Deadline', fmtDT(o.dueAt)]]} /></Section><SidePanel k={key('order', o.id)} label={o.id} deadline={['completed', 'cancelled', 'refunded', 'unpaid'].includes(o.status) ? null : o.dueAt} /></>} />
    {dlg === 'info' && <ReasonDialog title="Request missing buyer information" fields={[{ k: 'text', label: 'What is needed (shown to buyer)', type: 'textarea', required: true }]} confirm="Send request" onClose={() => setDlg(null)} onSubmit={v => perform('staffRequestInfo', { orderId: o.id, text: v.text, reason: v.reason }, d => O.staffRequestInfo(d, staff, o.id, v.text, v.reason), 'Request sent')} />}
    {dlg === 'contact' && <ReasonDialog title="Contact a party" fields={[{ k: 'party', label: 'Recipient', type: 'select', options: [['buyer', 'Buyer'], ['seller', 'Seller']], initial: 'buyer' }, { k: 'text', label: 'Message', type: 'textarea', required: true }]} confirm="Send" onClose={() => setDlg(null)} onSubmit={v => perform('staffContact', { orderId: o.id, party: v.party, text: v.text, reason: v.reason }, d => O.staffContact(d, staff, o.id, v.party, v.text, v.reason), 'Message sent')} />}
    {dlg === 'ext' && <ReasonDialog title="Record an agreed extension" intro="Document an extension both parties agreed to. The original deadline stays in history." fields={[{ k: 'days', label: 'Extra days', type: 'number', required: true, initial: 2 }]} confirm="Record" onClose={() => setDlg(null)} onSubmit={v => perform('documentExtension', { orderId: o.id, days: +v.days, reason: v.reason }, d => O.documentExtension(d, staff, o.id, +v.days, v.reason), 'Extension recorded')} />}
    {dlg === 'cancel' && <ReasonDialog title={`Cancel ${o.id}`} danger intro={o.status === 'unpaid' ? 'Stops the unpaid workflow. A late payment would still be reconciled.' : 'Cancellation after payment needs a recorded agreement or decision. Any refund runs as a separate request with its own approval.'} fields={o.status === 'unpaid' ? [] : [{ k: 'basis', label: 'Agreement or decision reference', required: true }]} confirm="Cancel order" onClose={() => setDlg(null)} onSubmit={v => perform('staffCancelOrder', { orderId: o.id, basis: v.basis, reason: v.reason }, d => O.staffCancelOrder(d, staff, o.id, v.basis, v.reason), 'Order cancelled')} />}
    {dlg === 'esc' && <ReasonDialog title={`Escalate ${o.id}`} confirm="Escalate" onClose={() => setDlg(null)} onSubmit={v => perform('escalateOrder', { orderId: o.id, reason: v.reason }, d => O.escalateOrder(d, staff, o.id, v.reason), 'Escalated')} />}
  </>;
}

// ---------- Resolution Center
export function ACases() {
  const { db, staff, nav } = useApp(); const g = useGate(['c']); if (g) return g;
  const scoped = roleOf(db, staff).scope?.cases === 'assigned';
  const rows = db.cases.map(c => { const o = db.orders.find(x => x.id === c.orderId); return { ...c, o, as: assignment(db, key('case', c.id)).assigneeId }; }).filter(c => !scoped || !c.as || c.as === staff.id);
  return <><PageTitle title="Resolution Center" sub={scoped ? 'Showing cases assigned to you and unassigned cases you can claim.' : 'All cases.'} />
    <AList id="cases" rows={rows} search={c => `${c.id} ${c.orderId} ${name(db, c.buyerId)} ${db.stores[c.storeId].name}`} onOpen={c => nav({ page: 'a-case', id: c.id })}
      filters={[{ k: 's', label: 'Status', options: Object.keys(CASE_T).map(x => [x, x]), test: (c, v) => c.status === v }, { k: 'q', label: 'Queue', options: [['unassigned', 'Unassigned'], ['overdue', 'Overdue'], ['mine', 'Assigned to me']], test: (c, v) => v === 'unassigned' ? !c.as : v === 'mine' ? c.as === staff.id : c.deadline && c.deadline < now() && !['Resolved', 'Closed'].includes(c.status) }]}
      sorts={[{ id: 'dl', label: 'Deadline', fn: (a, b) => (a.deadline || 9e15) - (b.deadline || 9e15) }, { id: 'age', label: 'Oldest', fn: (a, b) => a.openedAt - b.openedAt }]}
      cols={[{ k: 'id', label: 'Case', render: c => <b>{c.id}</b> }, { k: 'o', label: 'Order', render: c => c.orderId }, { k: 'p', label: 'Buyer / seller', render: c => <span className="small">{name(db, c.buyerId)}<br />{db.stores[c.storeId].name}</span> }, { k: 'a', label: 'Amount', cls: 'num', render: c => money(c.o.total) },
        { k: 'i', label: 'Issue / outcome', render: c => <span className="small">{c.reason}<br /><span className="muted">{c.outcome}</span></span> }, { k: 's', label: 'Status', render: c => <Badge tone={CASE_T[c.status]} dot>{c.status}</Badge> }, { k: 'as', label: 'Assigned', render: c => staffName(db, c.as) }, { k: 'ag', label: 'Age', render: c => rel(c.openedAt).replace(' ago', '') },
        { k: 'dl', label: 'Response deadline', render: c => c.deadline && !['Resolved', 'Closed'].includes(c.status) ? <span className={c.deadline < now() ? 'bad-t' : ''}>{rel(c.deadline)}</span> : '—' }, { k: 'e', label: 'Escalation', cls: 'num', render: c => c.escalation || 0 }]} /></>;
}
export function ACase() {
  const { db, staff, route, nav, act, perform } = useApp(); const g = useGate(['c', route.id]); const c0 = db.cases.find(x => x.id === route.id); const [seen, setSeen] = useState(c0?.version); useEffect(() => { if (seen == null && c0) setSeen(c0.version); }); const [dlg, setDlg] = useState(null); const [msg, setMsg] = useState(''); if (g) return g;
  const c = c0; if (!c) return <Empty title="Case not found" />;
  const as = assignment(db, key('case', c.id)).assigneeId;
  if (roleOf(db, staff).scope?.cases === 'assigned' && as && as !== staff.id) return <Empty icon="lock" title="Access denied">This case is assigned to another reviewer. Your role sees assigned and unassigned cases only.</Empty>;
  const o = db.orders.find(x => x.id === c.orderId); const ob = orderBuckets(db, o.id); const dec = can(db, staff, 'cases.decide'); const closed = ['Resolved', 'Closed'].includes(c.status);
  const stale = seen != null && seen !== c.version;
  const run = async (name, args, fn, m) => { const r = await perform(name, args, fn, m); if (r.ok) setSeen(null); else if (r.error.code === 'stale') setSeen(c.version); return r; };
  const v = seen ?? c.version;
  const refund = c.remedy?.refundId && db.refunds.find(r => r.id === c.remedy.refundId);
  return <>
    <DetailHead back={{ label: 'Resolution Center', route: { page: 'a-cases' } }} refId={c.orderId} title={c.id} badges={<><Badge tone={CASE_T[c.status]} dot>{c.status}</Badge>{c.escalation > 0 && <Badge tone="bad">Escalation level {c.escalation}</Badge>}{c.holdActive && <Badge tone="warn">Seller funds held</Badge>}<Badge tone="muted">Version {c.version}</Badge></>}
      amounts={[['Order', money(o.total)], ['Held for this order', fmtMoney(ob.held)], c.remedy?.amountC && ['Remedy amount', fmtMoney(c.remedy.amountC)]]}
      actions={dec ? <>{!closed && <><Btn size="sm" v="primary" onClick={() => setDlg('decide')}>Record decision</Btn><Btn size="sm" onClick={() => setDlg('info')}>Request information</Btn></>}{c.remedy && c.remedy.state !== 'Implemented' && <Btn size="sm" onClick={() => setDlg('verify')}>Verify remedy</Btn>}{c.status === 'Resolved' && <Btn size="sm" onClick={() => setDlg('close')}>Close case</Btn>}{closed && <Btn size="sm" v="ghost" onClick={() => setDlg('appeal')}>Record review request</Btn>}</> : <span className="xs muted">View only.</span>} />
    {stale && <Notice tone="warn" title="Case updated" action={<Btn size="sm" onClick={() => setSeen(c.version)}>I have reviewed the latest version</Btn>}>Someone changed this case after you opened it (version {seen} → {c.version}). Actions are blocked until you review.</Notice>}
    {c.remedy && <Notice tone={c.remedy.state === 'Implemented' ? 'ok' : 'info'} title={`Outcome: ${c.remedy.type}${c.remedy.amountC ? ' ' + fmtMoney(c.remedy.amountC) : ''}`}>Remedy state: <b>{c.remedy.state}</b>{refund && <> · Refund {refund.id}: approval <b>{db.approvals.find(a => a.id === refund.approvalId)?.status}</b>, provider <b>{refund.status}</b> <button className="linkbtn" onClick={() => nav({ page: 'a-refund', id: refund.id })}>Open refund</button></>}. {c.remedy.state !== 'Implemented' ? 'The case stays open until the remedy is implemented.' : ''}</Notice>}
    <DetailGrid main={<DTabs tabs={[
      { id: 'ov', label: 'Overview', body: <><Section title="Complaint"><KV items={[['Issue', c.reason], ['Requested outcome', c.outcome], ['Opened', fmtDT(c.openedAt)], ['Response deadline', c.deadline ? `${fmtDT(c.deadline)} (${rel(c.deadline)})` : '—']]} /><p>{c.description}</p></Section>
        <Section title="Purchased terms"><KV items={[['Package', `${o.snap.pkgName}: ${o.snap.pkgDesc}`], ['Replacement terms', o.snap.replacement], ['Payment', `${o.payment.status} · ${money(o.total)}`], ['Fulfilment', STATUS_LABEL[o.status]]]} /></Section>
        <Section title="Messages to both parties"><p className="xs muted">Public. Buyer and seller both see these.</p>{(c.staffMsgs || []).map((m, i) => <div key={i} className="pv-row"><span className="staff-tag">Marketplace support</span><span className="small">{m.text}</span><span className="xs muted">{fmtDT(m.at)}</span></div>)}{c.responses.map((r, i) => <div key={'r' + i} className="pv-row"><b className="xs">{r.from}</b><span className="small">{r.text}</span><span className="xs muted">{fmtDT(r.at)}</span></div>)}
          {dec && !closed && <div className="inline-form"><textarea rows="2" aria-label="Public message to both parties" placeholder="Public message to buyer and seller" value={msg} onChange={e => setMsg(e.target.value)} /><Btn size="sm" disabled={!msg.trim() || stale} onClick={async () => { const r = await run('casePublicMessage', { caseId: c.id, text: msg, version: v }, d => O.casePublicMessage(d, staff, c.id, msg, v), 'Message sent to both parties'); if (r.ok) setMsg(''); }}>Send public message</Btn></div>}</Section>
        <Section title="Internal notes from the review (staff only)">{(c.internal || []).map((n, i) => <div key={i} className="int-note"><b className="xs">{n.by}</b> <span className="xs muted">{fmtDT(n.at)}</span><p className="small">{n.text}</p></div>)}{!(c.internal || []).length && <p className="muted small">None. Use the internal notes panel to add one.</p>}</Section></> },
      { id: 'ev', label: 'Evidence', count: c.evidence.length, body: <Section><Evidence perm="cases.evidence" label="Case evidence and delivery files" k={'case:' + c.id + ':evidence'}>{c.evidence.map((f, i) => <div key={i}><FileChip f={f} /><span className="xs muted">{f.by} · {fmtDate(f.at)}</span></div>)}{o.deliveries.map(dl => <div key={dl.v}><FileChip f={dl.file} locked /><span className="xs muted">Delivery v{dl.v} · {fmtDate(dl.at)}</span></div>)}</Evidence></Section> },
      { id: 'dec', label: 'Decisions', count: (c.decisions || []).length, body: <Section>{(c.decisions || []).length ? c.decisions.map((x, i) => <div key={i} className="restr"><b className="small">{x.type}{x.amountC ? ' ' + fmtMoney(x.amountC) : ''}</b> <span className="xs muted">{x.by} · {fmtDT(x.at)} · on case v{x.version}</span><p className="small">{x.rationale}</p><span className="xs">Evidence: {(x.evidence || []).join(', ') || '—'}</span></div>) : c.remedy ? <div className="restr"><b className="small">{c.remedy.type}</b> <span className="xs muted">{c.remedy.decidedBy}</span><p className="small">{c.remedy.rationale}</p></div> : <p className="muted small">No decision yet.</p>}{(c.appeals || []).map((a, i) => <Notice key={i} tone="warn" title={`Review requested by ${a.party}`}>{a.reason} · {fmtDT(a.at)}</Notice>)}</Section> },
      { id: 'tl', label: 'Timeline', body: <Section><Timeline events={c.timeline} /><h3 className="sub-h">Administrative actions</h3><AuditTrail objects={[c.id]} /></Section> },
    ]} />} side={<><Section title="Parties"><KV items={[['Buyer', name(db, c.buyerId)], ['Seller', db.stores[c.storeId].name], ['Order', <button className="linkbtn" onClick={() => nav({ page: 'a-order', id: o.id })}>{o.id}</button>]]} /></Section><SidePanel k={key('case', c.id)} label={c.id} deadline={closed ? null : c.deadline} eligiblePerm="cases.decide" /></>} />
    {dlg === 'decide' && <DecisionDialog c={c} o={o} onClose={() => setDlg(null)} onSubmit={x => run('caseDecision', { caseId: c.id, ...x, version: v }, d => O.caseDecision(d, staff, c.id, x, v), 'Decision recorded')} />}
    {dlg === 'info' && <ReasonDialog title="Request information" fields={[{ k: 'party', label: 'From', type: 'select', options: [['buyer', 'Buyer'], ['seller', 'Seller']], initial: 'seller' }, { k: 'text', label: 'Request (shown to the party)', type: 'textarea', required: true }]} confirm="Send request" onClose={() => setDlg(null)} onSubmit={x => run('caseRequestInfo', { caseId: c.id, party: x.party, text: x.text, reason: x.reason, version: v }, d => O.caseRequestInfo(d, staff, c.id, x.party, x.text, x.reason, v), 'Request sent')} />}
    {dlg === 'verify' && <ReasonDialog title="Verify remedy implemented" intro="Refunds must be confirmed by the provider; replacements must be delivered." confirm="Verify and resolve" onClose={() => setDlg(null)} onSubmit={x => run('caseVerifyRemedy', { caseId: c.id, reason: x.reason, version: v }, d => O.caseVerifyRemedy(d, staff, c.id, x.reason, v), 'Case resolved')} />}
    {dlg === 'close' && <ReasonDialog title="Close case" confirm="Close" onClose={() => setDlg(null)} onSubmit={x => run('caseClose', { caseId: c.id, reason: x.reason, version: v }, d => O.caseClose(d, staff, c.id, x.reason, v), 'Case closed')} />}
    {dlg === 'appeal' && <ReasonDialog title="Record request for review" intro={`Appeal window: ${S(db).appealDays} days after resolution (demo default). Reopens the case and assigns another eligible reviewer.`} fields={[{ k: 'party', label: 'Requested by', type: 'select', options: [['buyer', 'Buyer'], ['seller', 'Seller']], initial: 'buyer' }]} confirm="Reopen for review" onClose={() => setDlg(null)} onSubmit={x => run('caseAppeal', { caseId: c.id, party: x.party, reason: x.reason, version: v }, d => O.caseAppeal(d, staff, c.id, x.party, x.reason, v), 'Case reopened')} />}
  </>;
}
function DecisionDialog({ c, o, onClose, onSubmit }) {
  const { db, withInline } = useApp(); const rem = refundableC(db, o);
  const [type, setType] = useState('Partial refund'); const [amt, setAmt] = useState('20'); const [days, setDays] = useState('2'); const [why, setWhy] = useState(''); const [ev, setEv] = useState([]); const [err, setErr] = useState(''); const [confirm, setConfirm] = useState(false);
  const amountC = type === 'Full refund' ? rem : type === 'Partial refund' ? Math.round(+amt * 100) : type === 'Cancellation' ? rem : null;
  const files = c.evidence.map(f => f.name).concat(o.deliveries.map(dl => dl.file?.name).filter(Boolean));
  function next() { if (type === 'Partial refund' && !(amountC > 0 && amountC < rem)) return setErr(`Partial refund must be between $0.01 and ${fmtMoney(rem - 1)}.`); if (!why.trim()) return setErr('Record the rationale.'); if (!ev.length && files.length) return setErr('Select the evidence relied on.'); setErr(''); setConfirm(true); }
  return <Modal title={`Decision for ${c.id}`} onClose={onClose} footer={confirm ? <><Btn v="ghost" onClick={() => setConfirm(false)}>Back</Btn><Btn v="primary" onClick={async () => { const r = await withInline(() => onSubmit({ type, amountC, days: +days, rationale: why, evidence: ev })); if (r.ok) onClose(); else { setErr(r.error.message); setConfirm(false); } }}>Submit decision</Btn></> : <><Btn v="ghost" onClick={onClose}>Cancel</Btn><Btn v="primary" onClick={next}>Review outcome</Btn></>}>
    {!confirm ? <>
      <Field label="Outcome"><select value={type} onChange={e => setType(e.target.value)}>{['Replacement', 'New agreed deadline', 'Cancellation', 'No refund', 'Partial refund', 'Full refund'].map(x => <option key={x}>{x}</option>)}</select></Field>
      {type === 'Partial refund' && <Field label="Refund amount (USD)" hint={`Refundable: ${fmtMoney(rem)}`}><input type="number" value={amt} onChange={e => setAmt(e.target.value)} /></Field>}
      {type === 'New agreed deadline' && <Field label="Days from now"><input type="number" value={days} onChange={e => setDays(e.target.value)} /></Field>}
      <Field label="Rationale" required><textarea rows="3" value={why} onChange={e => setWhy(e.target.value)} /></Field>
      <fieldset className="types"><legend>Evidence relied on</legend>{files.map(f => <label key={f} className="radio"><input type="checkbox" checked={ev.includes(f)} onChange={e => setEv(e.target.checked ? [...ev, f] : ev.filter(x => x !== f))} />{f}</label>)}</fieldset>
      {err && <p className="ferr">{err}</p>}</> :
      <><Notice tone="warn" title="Check before submitting">{type}{amountC ? `: ${fmtMoney(amountC)} USD` : ''}{type === 'New agreed deadline' ? `: +${days} days` : ''}.</Notice>
        <KV items={[['Creates', amountC ? 'A linked refund request. It needs independent approval and provider confirmation. No money moves now.' : type === 'Replacement' ? 'A replacement request on the order. The case stays open until it is delivered and verified.' : type === 'No refund' ? 'Resolves the case and releases the seller hold.' : 'A new deadline on the order.'], ['Seller hold', type === 'No refund' ? 'Released' : amountC ? `Refund reverses ${fmtMoney(amountC - Math.round(amountC * o.commissionRate))} from the hold; the rest stays held until resolution` : 'Stays in place']]} /></>}
  </Modal>;
}

// ---------- support
export function ASupport() {
  const { db, nav } = useApp(); const g = useGate(['t']); if (g) return g;
  const rows = db.tickets.map(t => ({ ...t, as: assignment(db, key('ticket', t.id)).assigneeId, pr: assignment(db, key('ticket', t.id)).priority !== 'Normal' ? assignment(db, key('ticket', t.id)).priority : t.priority }));
  return <><PageTitle title="Support" sub="Closing a ticket never changes order, payment or case state." actions={<ExportButton name="Support tickets" rows={rows} cols={[['Ticket', r => r.id], ['Subject', r => r.subject], ['Status', r => r.status], ['Priority', r => r.pr], ['Assigned', r => staffName(db, r.as)]]} />} />
    <AList id="tickets" rows={rows} search={t => `${t.id} ${t.subject} ${t.name} ${t.order} ${t.link || ''}`} onOpen={t => nav({ page: 'a-ticket', id: t.id })}
      filters={[{ k: 's', label: 'Status', options: ['Open', 'Assigned', 'Awaiting customer', 'Awaiting internal action', 'Resolved', 'Closed'].map(x => [x, x]), test: (t, v) => t.status === v }, { k: 'a', label: 'Assignment', options: [['none', 'Unassigned'], ...Object.values(db.staff).filter(s => s.roles.includes('support')).map(s => [s.id, s.name])], test: (t, v) => v === 'none' ? !t.as : t.as === v }, { k: 'd', label: 'Deadline', options: [['over', 'Overdue']], test: t => t.deadline < now() && !['Resolved', 'Closed'].includes(t.status) }]}
      sorts={[{ id: 'dl', label: 'Response deadline', fn: (a, b) => a.deadline - b.deadline }, { id: 'new', label: 'Newest', fn: (a, b) => b.at - a.at }]}
      cols={[{ k: 'id', label: 'Ticket', render: t => <b>{t.id}</b> }, { k: 's', label: 'Subject', render: t => <span className="small">{t.subject}</span> }, { k: 'r', label: 'Requester', render: t => t.name }, { k: 'l', label: 'Related', render: t => <span className="xs">{[t.order, t.link].filter(Boolean).join(' · ') || '—'}</span> }, { k: 'c', label: 'Category', render: t => t.cat }, { k: 'p', label: 'Priority', render: t => <Badge tone={{ High: 'warn', Urgent: 'bad' }[t.pr] || 'muted'}>{t.pr}</Badge> }, { k: 'st', label: 'Status', render: t => <Badge tone="muted">{t.status}</Badge> }, { k: 'as', label: 'Assigned', render: t => staffName(db, t.as) }, { k: 'cr', label: 'Created', render: t => rel(t.at) }, { k: 'lr', label: 'Last response', render: t => rel(t.lastResponse) }, { k: 'dl', label: 'Deadline', render: t => <span className={t.deadline < now() && !['Resolved', 'Closed'].includes(t.status) ? 'bad-t' : ''}>{rel(t.deadline)}</span> }]} /></>;
}
const TEMPLATES = [['Status update', 'Thanks for your patience. Your request is with the team handling it. We will update you here when the linked record changes.'], ['Need information', 'To look into this, please reply with the order number and a short description of what you expected.'], ['Case guidance', 'You can add evidence and responses directly in the Resolution Center case. Both you and the other party see those messages.']];
export function ATicket() {
  const { db, staff, route, nav, act, perform } = useApp(); const g = useGate(['t', route.id]); const [pub, setPub] = useState(''); const [int, setInt] = useState(''); const [dlg, setDlg] = useState(null); if (g) return g;
  const t = db.tickets.find(x => x.id === route.id); if (!t) return <Empty title="Ticket not found" />;
  const reply = can(db, staff, 'support.reply');
  const linkRoute = t.link?.startsWith('CASE') ? { page: 'a-case', id: t.link } : t.link?.startsWith('PAY') ? { page: 'a-payout', id: t.link } : t.link?.startsWith('RF') ? { page: 'a-refund', id: t.link } : null;
  return <>
    <DetailHead back={{ label: 'Support', route: { page: 'a-support' } }} refId={t.id} title={t.subject} badges={<><Badge tone="muted">{t.status}</Badge><Badge tone="muted">{t.cat}</Badge>{t.escalated && <Badge tone="warn">Escalated</Badge>}</>}
      actions={reply && <><select aria-label="Change status" value="" onChange={e => e.target.value && setDlg({ status: e.target.value })}><option value="">Change status…</option>{['Open', 'Assigned', 'Awaiting customer', 'Awaiting internal action', 'Resolved', 'Closed'].filter(x => x !== t.status).map(x => <option key={x}>{x}</option>)}</select><Btn size="sm" onClick={() => setDlg('link')}>Link record</Btn><Btn size="sm" v="ghost" onClick={() => setDlg('esc')}>Escalate</Btn></>} />
    <DetailGrid main={<><Section title="Conversation">{t.thread.map((m, i) => <div key={i} className={'tmsg ' + m.kind}>{m.kind === 'internal' ? <span className="int-label"><Icon n="lock" s={12} /> Internal note · not visible to the customer</span> : <span className="xs muted">{m.from === 'customer' ? 'Customer' : 'Public reply'}</span>}<b className="xs">{m.by}</b> <span className="xs muted">{fmtDT(m.at)}</span><p className="small">{m.text}</p></div>)}</Section>
      {reply ? <div className="two-col"><Section title="Public reply"><select aria-label="Template" value="" onChange={e => e.target.value && setPub(e.target.value)}><option value="">Insert template…</option>{TEMPLATES.map(([n, x]) => <option key={n} value={x}>{n}</option>)}</select><textarea rows="4" aria-label="Public reply" value={pub} onChange={e => setPub(e.target.value)} placeholder="Visible to the customer" /><p className="xs muted">Templates are editable and never promise a refund, payout or date the linked workflow has not authorised.</p><Btn v="primary" size="sm" disabled={!pub.trim()} onClick={async () => { const r = await perform('ticketReply', { ticketId: t.id, text: pub, kind: 'public' }, d => O.ticketReply(d, staff, t.id, pub, 'public'), 'Reply sent'); if (r.ok) setPub(''); }}>Send public reply</Btn></Section>
        <Section title="Internal note"><textarea rows="4" aria-label="Internal note" value={int} onChange={e => setInt(e.target.value)} placeholder="Staff only" /><Btn size="sm" disabled={!int.trim()} onClick={async () => { const r = await perform('ticketReply', { ticketId: t.id, text: int, kind: 'internal' }, d => O.ticketReply(d, staff, t.id, int, 'internal'), 'Note added'); if (r.ok) setInt(''); }}>Add internal note</Btn></Section></div> : <Notice tone="info">View only.</Notice>}
      <Section title="Timeline"><AuditTrail objects={[t.id]} /></Section></>}
      side={<><Section title="Requester"><KV items={[['Name', t.name], ['Email', maskEmail(t.email)], ['Related order', t.order || '—'], ['Linked record', linkRoute ? <button className="linkbtn" onClick={() => nav(linkRoute)}>{t.link}</button> : t.link || '—'], ['Created', fmtDT(t.at)], ['Response deadline', fmtDT(t.deadline)]]} /></Section><SidePanel k={key('ticket', t.id)} label={t.id} deadline={['Resolved', 'Closed'].includes(t.status) ? null : t.deadline} eligiblePerm="support.reply" /></>} />
    {dlg?.status && <ReasonDialog title={`Set status: ${dlg.status}`} intro="Only the ticket changes. Linked orders, payments and cases keep their own state." confirm="Update" onClose={() => setDlg(null)} onSubmit={v => perform('ticketStatus', { ticketId: t.id, status: dlg.status, reason: v.reason }, d => O.ticketStatus(d, staff, t.id, dlg.status, v.reason), 'Ticket updated')} />}
    {dlg === 'link' && <ReasonDialog title="Link a record" fields={[{ k: 'ref', label: 'Reference', type: 'select', options: [...db.cases.map(c => c.id), ...db.refunds.map(r => r.id), ...db.payouts.map(p => p.id)], initial: db.cases[0]?.id }]} confirm="Link" onClose={() => setDlg(null)} onSubmit={v => perform('ticketLink', { ticketId: t.id, ref: v.ref }, d => O.ticketLink(d, staff, t.id, v.ref), 'Linked')} />}
    {dlg === 'esc' && <ReasonDialog title="Escalate ticket" confirm="Escalate" onClose={() => setDlg(null)} onSubmit={v => perform('ticketEscalate', { ticketId: t.id, reason: v.reason }, d => O.ticketEscalate(d, staff, t.id, v.reason), 'Escalated')} />}
  </>;
}
