import React from 'react';
import { now, DAY, HOUR } from '@crateline/domain/clock.js';
import { CATEGORIES } from '@crateline/domain/data.js';
import { DomainError, fmtMoney, can, need, roleOf, isSuper, activeSupers, audit, nid, PERM_GROUPS, ALL_PERMS, ROLE_TEMPLATES, roleDiff, proposeRoleChange, deactivateStaff, proposeSetting, SENSITIVE, commissionFor, createApproval, requiredAuthority, publishPolicy, platformTotals, sellerFundsAll, storeBuckets, S, snotify, staffWith, ROUNDING } from '@crateline/domain/fin.js';
import { fmtDT, fmtDate, rel, tzName, money } from '@crateline/domain/logic.js';
import { Icon, Btn, Badge, Avatar, Modal, Field, Notice, Empty, Table, KV, Section, Stat, Sim, Seg, Toggle, useApp } from './ui.jsx';
import { M, useGate, PageTitle, AList, DetailHead, DTabs, DetailGrid, ReasonDialog, AuditTrail, ExportButton, ROUTES, canRoute } from './admin-ui.jsx';
import { queueItems } from './admin-ops.jsx';
import * as O from '@crateline/domain/ops.js';
import { apiEnabled } from './api.js';
const { useState } = React;
const fail = m => { throw new DomainError(m); };
const SV_T = { Draft: 'muted', 'Pending approval': 'info', Scheduled: 'accent', Active: 'ok', Superseded: 'muted', Rejected: 'bad' };

// ---------- overview
export function SAOverview() {
  const { db, staff, nav } = useApp(); const g = useGate(['sao']); const [range, setRange] = useState(30); if (g) return g;
  const since = now() - range * DAY; const t = platformTotals(db, e => e.at >= since); const all = platformTotals(db); const f = sellerFundsAll(db);
  const pend = db.approvals.filter(a => a.status === 'Pending');
  const ex = db.recon.filter(r => r.status === 'Open').length + db.integrations.filter(i => i.health !== 'Operational' && i.enabled).length + db.tasks.filter(x => x.status === 'Failed').length;
  const items = queueItems(db, staff); const by = {}; items.forEach(i => by[i.type] = (by[i.type] || 0) + 1);
  return <><PageTitle title="Business overview" sub={`USD only (other currencies are not enabled). Period: last ${range} days by transaction event date, ${tzName}.`} actions={<Seg label="Period" value={range} onChange={setRange} options={[{ id: 7, label: '7 d' }, { id: 30, label: '30 d' }, { id: 365, label: '12 m' }]} />} />
    <div className="stats">
      <Stat label="Gross sales volume" value={fmtMoney(t.gross)} sub={`All time ${fmtMoney(all.gross)}`} onClick={() => nav({ page: 'sa-bizreports' })} />
      <Stat label="Net platform commission" value={fmtMoney(t.netRevenue)} sub={`Gross ${fmtMoney(t.comm)} − reversed ${fmtMoney(t.commRev)}`} onClick={() => nav({ page: 'sa-bizreports' })} />
      <Stat label="Refunds confirmed" value={fmtMoney(t.refunded)} onClick={() => nav({ page: 'a-refunds' })} />
      <Stat label="Completed orders" value={db.orders.filter(o => o.status === 'completed' && o.completedAt >= since).length} onClick={() => nav({ page: 'a-orders' })} />
      <Stat label="Active sellers" value={Object.values(db.stores).filter(s => s.status === 'Active').length} sub={`of ${Object.keys(db.stores).length} stores`} onClick={() => nav({ page: 'a-sellers' })} />
      <Stat label="Open disputes" value={db.cases.filter(c => !['Resolved', 'Closed'].includes(c.status)).length} onClick={() => nav({ page: 'a-cases' })} />
      <Stat label="Payouts in progress" value={fmtMoney(f.reserved)} sub={`${db.payouts.filter(p => ['Awaiting approval', 'Approved', 'Processing', 'Reconciliation required'].includes(p.status)).length} payouts reserved`} onClick={() => nav({ page: 'a-payouts' })} />
      <Stat label="Payment and integration exceptions" value={ex} tone={ex ? 'warn' : ''} onClick={() => nav({ page: 'sa-health' })} />
    </div>
    <h2 className="sec-h">Outstanding seller funds (current, USD)</h2>
    <div className="balance-row five">{[['Pending', f.pending], ['Dispute holds', f.held], ['Available', f.available], ['Payout reserved', f.reserved], ['Total held for sellers', f.total]].map(([k, c]) => <div key={k} className="bal"><span className="xs muted">{k}</span><b>{fmtMoney(c)}</b></div>)}</div>
    <div className="two-col"><Section title={`Approvals (${pend.length} pending)`} action={<button className="linkbtn" onClick={() => nav({ page: 'sa-approvals' })}>All approvals</button>}>
      {pend.length ? <ul className="mini-orders">{pend.slice(0, 6).map(a => <li key={a.id}><button onClick={() => nav({ page: 'sa-approval', id: a.id })}><Badge tone="info">{a.type}</Badge><div className="mo-main"><b>{a.title}</b><span className="xs muted">{a.requester} · {rel(a.createdAt)}</span></div><div className="mo-side">{a.amountC ? <M c={a.amountC} /> : null}</div></button></li>)}</ul> : <p className="muted small">No pending approvals.</p>}</Section>
      <Section title="Modules needing attention"><ul className="activity">{Object.entries(by).map(([k, n]) => <li key={k}><button onClick={() => nav({ page: 'a-queue' })}><span className="small"><b>{n}</b> {k}</span></button></li>)}</ul>{!Object.keys(by).length && <p className="muted small">Nothing outstanding.</p>}</Section></div></>;
}

// ---------- staff and roles

export function SAStaff() {
  const { db, staff, nav, act, perform } = useApp(); const g = useGate(['sas']); const [tab, setTab] = useState('dir'); const [inv, setInv] = useState(false); const [role, setRole] = useState('support'); if (g) return g;
  const manage = can(db, staff, 'staff.manage'); const staffRows = Object.values(db.staff).map(s => ({ ...s, open: Object.values(db.assign).filter(a => a.assigneeId === s.id).length }));
  return <><PageTitle title="Staff and roles" sub="Permissions drive navigation, record access, exports and every action handler in this demo. Production needs the same checks on a trusted backend." actions={manage && <Btn icon="plus" onClick={() => setInv(true)}>Invite staff</Btn>} />
    <div className="tabs">{[['dir', 'Directory'], ['roles', 'Role editor'], ['inv', 'Invitations']].map(([id, l]) => <button key={id} className={tab === id ? 'on' : ''} onClick={() => setTab(id)}>{l}</button>)}</div>
    {tab === 'dir' && <AList id="staff" rows={staffRows} search={s => `${s.id} ${s.name} ${s.email}`} onOpen={s => nav({ page: 'sa-staffer', id: s.id })}
      filters={[{ k: 'a', label: 'State', options: [['1', 'Active'], ['0', 'Inactive']], test: (s, v) => String(+s.active) === v }, { k: 'r', label: 'Role', options: Object.values(db.roles).map(r => [r.id, r.name]), test: (s, v) => s.roles.includes(v) }]}
      cols={[{ k: 'id', label: 'Staff ID', render: s => <code className="xs">{s.id}</code> }, { k: 'n', label: 'Name', render: s => <><b className="small">{s.name}</b><span className="xs muted block">{s.email}</span></> }, { k: 'r', label: 'Roles', render: s => <div className="badges">{s.roles.map(r => <Badge key={r} tone={r === s.activeRole ? 'accent' : 'muted'}>{db.roles[r].name}</Badge>)}</div> }, { k: 't', label: 'Team', render: s => s.team }, { k: 'a', label: 'State', render: s => <Badge tone={s.active ? 'ok' : 'muted'}>{s.active ? 'Active' : 'Inactive'}</Badge> }, { k: 'f', label: '2FA', render: s => s.twoFA ? 'Set up' : 'Not set up' }, { k: 'l', label: 'Last sign-in', render: s => rel(s.lastSignIn) }, { k: 'o', label: 'Assignments', cls: 'num', render: s => s.open }]} />}
    {tab === 'roles' && <RoleEditor roleId={role} setRole={setRole} />}
    {tab === 'inv' && <Section><Table rows={db.invites} cols={[{ k: 'e', label: 'Email', render: i => i.email }, { k: 'r', label: 'Role', render: i => db.roles[i.role].name }, { k: 'b', label: 'Invited by', render: i => i.by }, { k: 'x', label: 'Expires', render: i => fmtDate(i.expiresAt) }, { k: 's', label: 'State', render: i => <Badge tone={{ Pending: 'info', Accepted: 'ok' }[i.status] || 'muted'}>{i.status}</Badge> },
      { k: 'a', label: '', render: i => i.status === 'Pending' && manage && <div className="row-acts">{!apiEnabled && <Btn size="sm" onClick={() => perform(null, null, d => O.inviteAction(d, staff, i.id, 'accept'), 'Invite accepted (simulated)')}>Simulate acceptance</Btn>}<Btn size="sm" v="ghost" onClick={() => perform('revokeInvite', { inviteId: i.id }, d => O.inviteAction(d, staff, i.id, 'revoke'), 'Invite revoked')}>Revoke</Btn></div> }]} /><p className="xs muted">Invitations are simulated records. No email is sent and no real credentials are requested.</p></Section>}
    {inv && <ReasonDialog title="Invite staff (simulated)" intro="Creates a pending invitation record. No email is sent." confirm="Create invite" fields={[{ k: 'email', label: 'Work email (example.com only)', required: true, initial: 'new.person@staff.example.com' }, { k: 'role', label: 'Role', type: 'select', options: Object.values(db.roles).map(r => [r.id, r.name]), initial: 'support' }]} onClose={() => setInv(false)} onSubmit={v => perform('inviteStaff', { email: v.email.trim(), role: v.role }, d => O.inviteStaff(d, staff, v.email.trim(), v.role), 'Invite created')} />}
  </>;
}
function RoleEditor({ roleId, setRole }) {
  const { db, staff, act, perform } = useApp(); const r = db.roles[roleId]; const [perms, setPerms] = useState(null); const [why, setWhy] = useState(''); const [err, setErr] = useState('');
  const cur = perms || r.perms; const diff = roleDiff(r.perms, cur); const holders = Object.values(db.staff).filter(s => s.roles.includes(roleId));
  const manage = can(db, staff, 'staff.manage');
  return <Section title={<span className="row-gap"><select aria-label="Role" value={roleId} onChange={e => { setRole(e.target.value); setPerms(null); }}>{Object.values(db.roles).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select><Badge tone="muted">Version {r.version}</Badge><span className="xs muted">{holders.length} staff · scope: {r.scope?.cases === 'assigned' ? 'cases assigned to them' : 'all records'}{r.super ? ' · approval limit: none' : r.perms.includes('refunds.approve') ? ` · limits ${fmtMoney(S(db).financeRefundLimitC)} refunds, ${fmtMoney(S(db).financePayoutLimitC)} payouts (USD)` : ''}</span></span>}>
    <div className="matrix">{PERM_GROUPS.map(([g, ps]) => <fieldset key={g}><legend>{g}</legend>{ps.map(([p, l]) => <label key={p} className={'radio' + (diff.added.includes(p) ? ' added' : diff.removed.includes(p) ? ' removed' : '')}><input type="checkbox" disabled={!manage} checked={cur.includes(p)} onChange={e => setPerms(e.target.checked ? [...cur, p] : cur.filter(x => x !== p))} />{l}</label>)}</fieldset>)}</div>
    {perms && (diff.added.length || diff.removed.length) ? <div className="role-diff"><p className="small"><b>Added:</b> {diff.added.join(', ') || 'none'} · <b>Removed:</b> {diff.removed.join(', ') || 'none'} · <b>Affects:</b> {holders.map(h => h.name).join(', ') || 'no one'}</p>
      <Field label="Reason" required><input value={why} onChange={e => setWhy(e.target.value)} /></Field>{err && <p className="ferr">{err}</p>}
      <div className="row-gap"><Btn v="primary" onClick={async () => { const x = await perform('proposeRoleChange', { roleId, perms: cur, reason: why }, d => proposeRoleChange(d, d.staff[staff.id], roleId, cur, why), 'Saved'); if (x.ok) { setPerms(null); setWhy(''); setErr(x.value.approval ? '' : ''); if (x.value.approval) setErr(`Sensitive change sent for independent approval (${x.value.approval.id}).`); } else setErr(x.error.message); }}>Save role version {r.version + 1}</Btn><Btn v="ghost" onClick={() => setPerms(null)}>Discard</Btn></div>
      <p className="xs muted">Adding financial, staff, settings or evidence authority, or changing a role you hold, needs another Super Admin to approve. Removals apply immediately.</p></div> : !manage && <p className="xs muted">View only.</p>}
    {err && !perms && <Notice tone="info">{err}</Notice>}
    {r.history?.length > 0 && <details><summary className="small">Previous versions</summary>{r.history.map(h => <p key={h.v} className="xs">v{h.v} · {h.by} · {fmtDT(h.at)} · {h.perms.length} permissions</p>)}</details>}
  </Section>;
}
export function SAStaffer() {
  const { db, staff, route, nav, act, perform } = useApp(); const g = useGate(['sf', route.id]); const [dlg, setDlg] = useState(null); const [roles, setRoles] = useState(null); if (g) return g;
  const s = db.staff[route.id]; if (!s) return <Empty title="Staff member not found" />;
  const manage = can(db, staff, 'staff.manage'); const r = roles || s.roles;
  const assigned = Object.entries(db.assign).filter(([, a]) => a.assigneeId === s.id);
  const approvals = db.approvals.filter(a => a.approverId === s.id || a.requesterId === s.id);
  const lim = role => role === 'superadmin' ? 'No limit' : db.roles[role].perms.includes('refunds.approve') ? `Refunds ≤ ${fmtMoney(S(db).financeRefundLimitC)}, payouts ≤ ${fmtMoney(S(db).financePayoutLimitC)}` : 'None';
  return <>
    <DetailHead back={{ label: 'Staff', route: { page: 'sa-staff' } }} refId={s.id} title={s.name} badges={<><Badge tone={s.active ? 'ok' : 'muted'}>{s.active ? 'Active' : 'Inactive'}</Badge>{s.roles.map(x => <Badge key={x} tone="muted">{db.roles[x].name}</Badge>)}</>}
      actions={manage && <>{s.active ? <Btn v="danger" size="sm" onClick={() => setDlg('deact')}>Deactivate</Btn> : <Btn size="sm" onClick={() => setDlg('react')}>Reactivate</Btn>}<Btn size="sm" disabled={!s.sessions.length} onClick={() => setDlg('revoke')}>Revoke all sessions</Btn></>} />
    <DetailGrid main={<><Section title="Profile"><KV items={[['Email', s.email], ['Team', s.team], ['Two-factor', s.twoFA ? 'Set up (codes never shown)' : 'Not set up'], ['Last sign-in', fmtDT(s.lastSignIn)], ['Password', 'Never shown']]} /></Section>
      <Section title="Roles and approval authority">{Object.values(db.roles).map(x => <label key={x.id} className="radio"><input type="checkbox" disabled={!manage} checked={r.includes(x.id)} onChange={e => setRoles(e.target.checked ? [...r, x.id] : r.filter(y => y !== x.id))} />{x.name} <span className="xs muted">· {lim(x.id)}</span></label>)}
        {roles && <div className="row-gap"><Btn v="primary" size="sm" onClick={() => setDlg('roles')}>Save role assignment</Btn><Btn size="sm" v="ghost" onClick={() => setRoles(null)}>Discard</Btn></div>}</Section>
      <Section title={`Active sessions (${s.sessions.length})`}>{s.sessions.length ? s.sessions.map(x => <div key={x.id} className="row-between"><span className="small">{x.device} · {fmtDT(x.at)}</span>{manage && <Btn size="sm" v="ghost" onClick={() => setDlg({ one: x.id })}>Revoke</Btn>}</div>) : <p className="muted small">No sessions.</p>}</Section>
      <Section title={`Assignments (${assigned.length})`}>{assigned.map(([k]) => <p key={k} className="small">{k}</p>)}{!assigned.length && <p className="muted small">None.</p>}</Section>
      <Section title="Approvals requested or decided">{approvals.map(a => <p key={a.id} className="small"><button className="linkbtn" onClick={() => nav({ page: 'sa-approval', id: a.id })}>{a.id}</button> {a.title} · {a.status}</p>)}{!approvals.length && <p className="muted small">None.</p>}</Section></>}
      side={<Section title="Privileged activity"><AuditTrail objects={[s.id]} />{db.audit.filter(a => a.actorId === s.id).slice(0, 8).map(a => <p key={a.id} className="xs">{fmtDT(a.at)} · {a.action} · {a.object}</p>)}</Section>} />
    {dlg === 'deact' && <ReasonDialog title={`Deactivate ${s.name}`} danger intro="Ends sessions, blocks new actions, moves assignments to the unassigned queue, and returns any unexecuted approvals they gave for re-approval. The last active Super Admin cannot be deactivated." confirm="Deactivate" onClose={() => setDlg(null)} onSubmit={v => perform('deactivateStaff', { staffId: s.id, reason: v.reason }, d => deactivateStaff(d, d.staff[staff.id], s.id, v.reason), 'Staff deactivated')} />}
    {dlg === 'react' && <ReasonDialog title={`Reactivate ${s.name}`} confirm="Reactivate" onClose={() => setDlg(null)} onSubmit={v => perform('reactivateStaff', { staffId: s.id, reason: v.reason }, d => O.reactivateStaff(d, staff, s.id, v.reason), 'Reactivated')} />}
    {dlg === 'revoke' && <ReasonDialog title="Revoke all sessions" confirm="Revoke" onClose={() => setDlg(null)} onSubmit={v => perform('revokeSessions', { staffId: s.id, reason: v.reason }, d => O.revokeSessions(d, staff, s.id, v.reason), 'Sessions revoked')} />}
    {dlg?.one && <ReasonDialog title="Revoke session" confirm="Revoke" onClose={() => setDlg(null)} onSubmit={v => perform('revokeSessions', { staffId: s.id, reason: v.reason, sessionId: dlg.one }, d => O.revokeSessions(d, staff, s.id, v.reason, dlg.one), 'Session revoked')} />}
    {dlg === 'roles' && <ReasonDialog title="Save role assignment" intro={`New roles: ${r.map(x => db.roles[x].name).join(', ')}. Adding sensitive authority or changing your own roles needs another Super Admin.`} confirm="Save" onClose={() => setDlg(null)} onSubmit={async v => { const x = await perform('proposeStaffRoles', { staffId: s.id, roles: r, reason: v.reason }, d => O.proposeStaffRoles(d, staff, s.id, r, v.reason)); if (x.ok) { setRoles(null); } return x; }} />}
  </>;
}

// ---------- settings
function SettingRow({ k, label, help, render, input, toValue }) {
  const { db, staff, act, perform } = useApp(); const [edit, setEdit] = useState(false); const [val, setVal] = useState(''); const [eff, setEff] = useState('now'); const [why, setWhy] = useState(''); const [err, setErr] = useState('');
  const cur = S(db)[k]; const sens = SENSITIVE.includes(k); const pend = db.settings.versions.find(v => v.key === k && ['Pending approval', 'Scheduled'].includes(v.state));
  return <div className="setrow"><div className="set-main"><b className="small">{label}</b>{sens && <Badge tone="info">Needs approval</Badge>}<span className="xs muted block">{help}</span></div><div className="set-val">{render(cur)}</div>
    <div className="set-act">{pend ? <span className="xs"><Badge tone={SV_T[pend.state]}>{pend.state}</Badge> → {render(pend.to)}{pend.state === 'Scheduled' ? ` from ${fmtDT(pend.effectiveAt)}` : ''}</span> : can(db, staff, 'settings.edit') && !edit && <Btn size="sm" onClick={() => { setEdit(true); setVal(input.from(cur)); }}>Change</Btn>}</div>
    {edit && <div className="set-edit">{input.el(val, setVal)}<select aria-label="Effective" value={eff} onChange={e => setEff(e.target.value)}><option value="now">Effective now</option><option value="1d">Effective in 1 day</option><option value="7d">Effective in 7 days</option></select><input aria-label="Reason" placeholder="Reason (required)" value={why} onChange={e => setWhy(e.target.value)} />
      <Btn size="sm" v="primary" onClick={async () => { let v; try { v = toValue(val); } catch (e) { return setErr(e.message); } const at = eff === 'now' ? now() : now() + (eff === '1d' ? 1 : 7) * DAY; const x = await perform('proposeSetting', { key: k, value: v, reason: why, effectiveAt: at }, d => proposeSetting(d, d.staff[staff.id], k, v, why, at), sens ? 'Sent for independent approval' : eff === 'now' ? 'Setting active' : 'Setting scheduled'); if (x.ok) { setEdit(false); setWhy(''); setErr(''); } else setErr(x.error.message); }}>{sens ? 'Submit for approval' : 'Save'}</Btn><Btn size="sm" v="ghost" onClick={() => { setEdit(false); setErr(''); }}>Cancel</Btn>{err && <span className="ferr">{err}</span>}</div>}
  </div>;
}
const num = (min, max, scale = 1) => ({ from: c => String(c / scale), el: (v, s) => <input type="number" aria-label="New value" value={v} onChange={e => s(e.target.value)} /> });
const toNum = (min, max, scale = 1) => v => { const n = +v; if (v === '' || isNaN(n) || n < min || n > max) throw new Error(`Enter a number between ${min} and ${max}.`); return Math.round(n * scale * 1e6) / 1e6; };
function Versions({ keys }) { const { db } = useApp(); const rows = db.settings.versions.filter(v => !keys || keys.includes(v.key)); return <Section title="Version history"><Table rows={rows} empty={<p className="muted small">No changes yet.</p>} cols={[{ k: 'id', label: 'Version', render: v => <code className="xs">{v.id}</code> }, { k: 'k', label: 'Setting', render: v => v.key }, { k: 'c', label: 'Change', render: v => <span className="xs">{JSON.stringify(v.from)} → {JSON.stringify(v.to)}</span> }, { k: 'b', label: 'By', render: v => v.by }, { k: 'e', label: 'Effective', render: v => fmtDT(v.effectiveAt) }, { k: 's', label: 'State', render: v => <Badge tone={SV_T[v.state]}>{v.state}</Badge> }, { k: 'r', label: 'Reason', render: v => <span className="xs">{v.reason}</span> }]} /><p className="xs muted">Existing orders and accepted offers keep the terms they were bought with. Changes never recalculate past earnings.</p></Section>; }

export function SASettings() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['sset']); if (g) return g; const s = S(db);
  const feat = (k, label, desc) => <Toggle key={k} checked={s.features[k]} onChange={v => perform('proposeSetting', { key: 'features', value: { ...S(db).features, [k]: v }, reason: `${label} ${v ? 'enabled' : 'disabled'} from settings` }, d => proposeSetting(d, d.staff[staff.id], 'features', { ...S(d).features, [k]: v }, `${label} ${v ? 'enabled' : 'disabled'} from settings`), `${label} ${v ? 'enabled' : 'disabled'}. Existing records are preserved`)} label={label} desc={desc} />;
  return <><PageTitle title="Marketplace settings" sub="Low-impact changes save immediately with history. Commercial, threshold and retention changes need independent approval." />
    <Section title="Platform"><SettingRow k="platformName" label="Platform name" help="Shown in the header and emails (demo)." render={v => v} input={{ from: v => v, el: (v, set) => <input aria-label="Platform name" value={v} onChange={e => set(e.target.value)} /> }} toValue={v => { if (!v.trim()) throw new Error('Enter a name.'); return v.trim(); }} />
      <SettingRow k="listingApproval" label="Listing approval required" help="New and commercially changed listings go to Pending review." render={v => v ? 'Required' : 'Not required'} input={{ from: v => v ? 'yes' : 'no', el: (v, set) => <select aria-label="Listing approval" value={v} onChange={e => set(e.target.value)}><option value="yes">Required</option><option value="no">Not required</option></select> }} toValue={v => v === 'yes'} />
      <SettingRow k="storeLimit" label="Stores per seller account" help="One store per account at launch." render={v => v} input={num()} toValue={toNum(1, 5)} />
      <KV items={[['Markets', s.markets.join(', ')], ['Currencies enabled for money movement', s.currencies.join(', ') + ' only. Other currencies are not converted.'], ['Categories', CATEGORIES.filter(c => c.active).map(c => c.name).join(', ') + ' (manage in Categories)']]} /></Section>
    <Section title="Features"><p className="xs muted">Disabling a feature stops new use. Existing offers, reviews and follows remain, and outstanding transactions continue.</p>
      {feat('customOffers', 'Custom offers', 'Buyers can request offers; sellers can send them')}{feat('reviews', 'Reviews', 'Buyers can review completed orders')}{feat('follows', 'Seller follows', 'Buyers can follow stores')}{feat('scheduledPayouts', 'Scheduled payouts', 'Not available in this demo; manual requests only')}
      <KV items={[['Delivery methods', s.deliveryMethods.join(', ')]]} /></Section>
    <Versions keys={['platformName', 'listingApproval', 'storeLimit', 'features']} /></>;
}
export function SACommissions() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['scm']); const [amt, setAmt] = useState('100'); const [store, setStore] = useState('st_atlas'); const [dlg, setDlg] = useState(null); if (g) return g;
  const s = S(db); const st = db.stores[store]; const rule = commissionFor(db, store, st.cat); const c = Math.round(+amt * 100); const comm = Math.round(c * rule.rate);
  return <><PageTitle title="Commissions and fees" sub="Precedence: seller override, then category override, then platform default. Percentage rules only." />
    <Section title="Commission rules"><SettingRow k="commissionDefault" label="Platform default" help="Percentage of the product subtotal (0 to 100)." render={v => (v * 100).toFixed(2).replace(/\.00$/, '') + '%'} input={{ from: v => String(v * 100), el: (v, set) => <input type="number" aria-label="Percent" value={v} onChange={e => set(e.target.value)} /> }} toValue={v => toNum(0, 100)(v) / 100} />
      <div className="setrow"><div className="set-main"><b className="small">Category overrides</b><span className="xs muted block">Apply to new orders in that category.</span></div><div className="set-val">{Object.entries(s.commissionCategory).map(([k, v]) => `${k}: ${v * 100}%`).join(', ') || 'None'}</div><div className="set-act">{can(db, staff, 'settings.edit') && <Btn size="sm" onClick={() => setDlg('cat')}>Add or change</Btn>}</div></div>
      <div className="setrow"><div className="set-main"><b className="small">Seller overrides</b><span className="xs muted block">Highest precedence.</span></div><div className="set-val">{Object.entries(s.commissionSeller).map(([k, v]) => `${db.stores[k]?.name}: ${v * 100}%`).join(', ') || 'None'}</div><div className="set-act">{can(db, staff, 'settings.edit') && <Btn size="sm" onClick={() => setDlg('sel')}>Add or change</Btn>}</div></div></Section>
    <Section title="Preview calculator"><Notice tone="info">Preview only. It never performs a financial action.</Notice>
      <div className="form-grid"><Field label="Product subtotal"><input type="number" value={amt} onChange={e => setAmt(e.target.value)} /></Field><Field label="Currency"><select><option>USD</option></select></Field><Field label="Seller (for rule selection)"><select value={store} onChange={e => setStore(e.target.value)}>{Object.values(db.stores).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field></div>
      {c >= 0 && !isNaN(c) ? <KV items={[['Winning rule', `${rule.rule}: ${rule.rate * 100}%`], ['Commission', fmtMoney(comm)], ['Seller earnings', fmtMoney(c - comm) + ' before holds or payout reservations'], ['Refund example', `A ${fmtMoney(Math.round(c * 0.2))} refund reverses ${fmtMoney(Math.round(Math.round(c * 0.2) * rule.rate))} commission and ${fmtMoney(Math.round(c * 0.2) - Math.round(Math.round(c * 0.2) * rule.rate))} seller earnings`], ['Rounding', ROUNDING]]} /> : <p className="ferr">Enter a non-negative amount.</p>}</Section>
    <Section title="Fees (demo defaults)"><Table rows={[{ id: 1, n: 'Buyer service fee', who: 'Buyer', v: (s.buyerFeeRate * 100) + '%', r: 'Refundable with the order' }, { id: 2, n: 'Seller charges', who: 'Seller', v: (s.sellerChargeRate * 100) + '%', r: '—' }, { id: 3, n: 'Payment fees', who: 'Platform', v: (s.paymentFeeRate * 100) + '%', r: 'Not refundable' }, { id: 4, n: 'Payout fee', who: 'Seller', v: fmtMoney(s.payoutFeeC), r: 'Not refundable' }]} cols={[{ k: 'n', label: 'Fee', render: x => x.n }, { k: 'w', label: 'Borne by', render: x => x.who }, { k: 'v', label: 'Value', render: x => x.v }, { k: 'r', label: 'Refund treatment', render: x => x.r }]} /><p className="xs muted">All zero in this demo. If enabled, a fee appears in checkout, allocation, invoice and earnings entries consistently.</p></Section>
    <Versions keys={['commissionDefault', 'commissionCategory', 'commissionSeller']} />
    {dlg === 'cat' && <ReasonDialog title="Category override" intro="Sent for independent approval. Applies prospectively." fields={[{ k: 'cat', label: 'Category', type: 'select', options: CATEGORIES.map(x => [x.id, x.name]), initial: 'data' }, { k: 'pct', label: 'Percent (blank to remove)', type: 'number' }]} confirm="Submit for approval" onClose={() => setDlg(null)} onSubmit={v => { let m; try { m = { ...S(db).commissionCategory }; if (v.pct === '') delete m[v.cat]; else m[v.cat] = toNum(0, 100)(v.pct) / 100; } catch (e) { return { ok: false, error: e }; } return perform('proposeSetting', { key: 'commissionCategory', value: m, reason: v.reason }, d => proposeSetting(d, d.staff[staff.id], 'commissionCategory', m, v.reason), 'Sent for approval'); }} />}
    {dlg === 'sel' && <ReasonDialog title="Seller override" intro="Sent for independent approval. Applies prospectively." fields={[{ k: 'st', label: 'Seller', type: 'select', options: Object.values(db.stores).map(x => [x.id, x.name]), initial: 'st_atlas' }, { k: 'pct', label: 'Percent (blank to remove)', type: 'number' }]} confirm="Submit for approval" onClose={() => setDlg(null)} onSubmit={v => { let m; try { m = { ...S(db).commissionSeller }; if (v.pct === '') delete m[v.st]; else m[v.st] = toNum(0, 100)(v.pct) / 100; } catch (e) { return { ok: false, error: e }; } return perform('proposeSetting', { key: 'commissionSeller', value: m, reason: v.reason }, d => proposeSetting(d, d.staff[staff.id], 'commissionSeller', m, v.reason), 'Sent for approval'); }} />}
  </>;
}

// ---------- integrations and payout configuration
export function SAIntegrations() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['sint']); const testOutcome = db.scenario.testConn || 'success'; const [dlg, setDlg] = useState(null); if (g) return g;
  const ed = can(db, staff, 'integrations.edit');
  return <><PageTitle title="Payment integrations" sub="Requested capabilities, not claims about any real provider. This artifact never connects to live services and accepts no real keys." />
    <div className="int-grid">{db.integrations.map(p => <Section key={p.id} title={<span className="row-gap">{p.name}<Badge tone={p.enabled ? 'ok' : 'muted'}>{p.enabled ? 'Enabled' : 'Disabled'}</Badge><Badge tone={p.mode === 'Live' ? 'bad' : 'info'}>{p.mode} mode</Badge></span>}>
      <KV items={[['Methods', p.methods.join(', ')], ['Currencies', p.currencies.join(', ')], ['Markets', p.markets.join(', ')], ['Credentials', p.keyLabel ? p.keyLabel + ' (masked placeholder)' : <span className="bad-t">Not configured</span>], ['Callback', p.callback], ['Last simulated check', p.lastCheck ? `${fmtDT(p.lastCheck)} · ${p.health}` : 'Never'], ['Recent failures', p.failures]]} />
      {p.crypto && <><h3 className="sub-h">Crypto configuration</h3><KV items={[['Asset and network', p.crypto.pairs.map(([a, n]) => `${a} on ${n}`).join('; ')], ['Amount precision', p.crypto.precision + ' decimals'], ['Quote expiry', p.crypto.quoteMinutes + ' minutes'], ['Confirmations', p.crypto.confirmations], ['Underpayment', p.crypto.underpayment], ['Late payment', p.crypto.late], ['Unsupported networks', 'Recovery is not guaranteed']]} /></>}
      {ed && <div className="row-gap"><Btn size="sm" onClick={() => perform('testConnection', { integrationId: p.id, outcome: testOutcome }, d => O.testConnection(d, staff, p.id, d.scenario.testConn))}>Test connection ({testOutcome})</Btn><Btn size="sm" onClick={() => setDlg({ edit: p })}>Edit</Btn><Btn size="sm" v="ghost" onClick={() => setDlg({ toggle: p })}>{p.enabled ? 'Disable' : 'Enable'}</Btn><Btn size="sm" v="ghost" onClick={() => setDlg({ mode: p })}>Switch to {p.mode === 'Test' ? 'Live' : 'Test'}</Btn></div>}
    </Section>)}</div>
    {dlg?.edit && <ReasonDialog title={`Edit ${dlg.edit.name}`} intro="Configuration-shaped sample values only. Secrets use an approved secret manager in production, never this form." fields={[{ k: 'markets', label: 'Configured markets (comma separated)', required: true, initial: dlg.edit.markets.join(', ') }, { k: 'callback', label: 'Callback URL', required: true, initial: dlg.edit.callbackUrl || '' }]} confirm="Save" onClose={() => setDlg(null)} onSubmit={v => perform('saveProvider', { integrationId: dlg.edit.id, markets: v.markets, callback: v.callback, reason: v.reason }, d => O.saveProvider(d, staff, dlg.edit.id, v, v.reason), 'Saved')} />}
    {dlg?.toggle && <ReasonDialog title={`${dlg.toggle.enabled ? 'Disable' : 'Enable'} ${dlg.toggle.name}`} intro="Disabling stops new payment attempts only. Pending transactions, callbacks, reconciliation and refunds continue." confirm="Confirm" onClose={() => setDlg(null)} onSubmit={v => perform('toggleProvider', { integrationId: dlg.toggle.id, reason: v.reason }, d => O.toggleProvider(d, staff, dlg.toggle.id, v.reason), 'Provider updated')} />}
    {dlg?.mode && <ReasonDialog title={`Switch ${dlg.mode.name} to ${dlg.mode.mode === 'Test' ? 'Live' : 'Test'}`} danger intro="Environment changes need independent approval. Even when approved, this demo never connects to live services." confirm="Request change" onClose={() => setDlg(null)} onSubmit={v => perform('proposeIntegrationMode', { integrationId: dlg.mode.id, reason: v.reason }, d => O.proposeIntegrationMode(d, staff, dlg.mode.id, v.reason), 'Sent for approval')} />}
  </>;
}
export function SAPayoutSettings() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['sps']); const [prev, setPrev] = useState('st_atlas'); if (g) return g;
  const s = S(db); const ed = can(db, staff, 'settings.edit');
  const st = db.stores[prev]; const methods = db.payoutMethods[prev] || [];
  return <><PageTitle title="Payout and settlement" sub="Rule changes apply to new requests. Submitted payouts keep their original provider and destination." />
    <Section title="Settlement rules"><SettingRow k="releaseDays" label="Earnings release delay" help="Days after completion with no open hold." render={v => v + ' days'} input={num()} toValue={toNum(0, 60)} />
      <SettingRow k="payoutMinC" label="Minimum payout (USD)" help="Applies to new requests." render={v => fmtMoney(v)} input={num(0, 1e6, 100)} toValue={v => Math.round(toNum(1, 100000)(v) * 100)} />
      <SettingRow k="payoutFeeC" label="Payout fee (USD)" help="Zero in demo." render={v => fmtMoney(v)} input={num(0, 1e6, 100)} toValue={v => Math.round(toNum(0, 1000)(v) * 100)} />
      <SettingRow k="financeRefundLimitC" label="Finance Admin refund approval limit (USD)" help="Higher amounts need a Super Admin." render={v => fmtMoney(v)} input={num(0, 1e7, 100)} toValue={v => Math.round(toNum(0, 1e6)(v) * 100)} />
      <SettingRow k="financePayoutLimitC" label="Finance Admin payout approval limit (USD)" help="Higher amounts need a Super Admin." render={v => fmtMoney(v)} input={num(0, 1e7, 100)} toValue={v => Math.round(toNum(0, 1e6)(v) * 100)} />
      <KV items={[['Schedule', 'Manual requests only (scheduled payouts not enabled)'], ['Dispute holds', 'The affected order amount only, released or consumed once'], ['Destination changes', 'New review required; never silently substituted'], ['Other currencies', 'Need their own thresholds; never converted silently']]} /></Section>
    <Section title="Payout methods"><Table rows={db.payoutConfig.map(m => ({ ...m, id: m.type }))} cols={[{ k: 't', label: 'Method', render: m => <b className="small">{m.type}</b> }, { k: 'e', label: 'Enabled', render: m => <Badge tone={m.enabled ? 'ok' : 'muted'}>{m.enabled ? 'Enabled' : 'Disabled'}</Badge> }, { k: 'c', label: 'Currencies', render: m => m.currencies.join(', ') }, { k: 'f', label: 'Destination fields', render: m => <span className="xs">{m.fields}</span> }, { k: 'v', label: 'Verification', render: m => m.verify ? 'Required' : 'No' }, { k: 'mm', label: 'Min / max', render: m => `${fmtMoney(m.minC)} / ${fmtMoney(m.maxC)}` }, { k: 'fe', label: 'Fee', render: m => fmtMoney(m.feeC) }, { k: 'n', label: 'Notes', render: m => <span className="xs">{m.notes}</span> },
      { k: 'x', label: '', render: m => ed && <Btn size="sm" v="ghost" onClick={() => perform('togglePayoutMethod', { type: m.type }, d => O.togglePayoutMethod(d, staff, m.type), 'Method updated')}>{m.enabled ? 'Disable' : 'Enable'}</Btn> }]} /></Section>
    <Section title="Seller eligibility preview"><select aria-label="Seller" value={prev} onChange={e => setPrev(e.target.value)}>{Object.values(db.stores).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <Table rows={db.payoutConfig.map(m => { const own = methods.find(x => x.type === m.type); const why = st.status !== 'Active' ? `Store is ${st.status}` : !m.enabled ? 'Method not enabled' : !own ? 'Seller has not added this method' : !own.verified ? 'Destination not verified' : 'Available'; return { id: m.type, m, why }; })} cols={[{ k: 'm', label: 'Method', render: r => r.m.type }, { k: 'w', label: 'Eligibility', render: r => <Badge tone={r.why === 'Available' ? 'ok' : 'muted'}>{r.why}</Badge> }]} />
      <p className="xs muted">Location and currency come from the seller’s recorded profile, never the interface language.</p></Section>
    <Versions keys={['releaseDays', 'payoutMinC', 'payoutFeeC', 'financeRefundLimitC', 'financePayoutLimitC']} /></>;
}
export function SAOrderPolicies() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['sop']); if (g) return g; const s = S(db);
  return <><PageTitle title="Order and dispute policies" sub="Demo defaults. Fictional operating assumptions, not approved policy." />
    <Section title="Fulfilment"><KV items={[['Delivery clock starts', s.deliveryClock], ['Mandatory buyer information', 'Per listing; clock pauses until provided'], ['Extensions', 'Seller requests, buyer accepts or rejects; staff can record agreed extensions'], ['Cancellation', s.cancellation]]} />
      <SettingRow k="replacementDays" label="Replacement window (days after delivery)" help="Stored with each order at purchase." render={v => v + ' days'} input={num()} toValue={toNum(0, 90)} />
      <SettingRow k="replacementAttempts" label="Maximum replacement attempts" help="" render={v => v} input={num()} toValue={toNum(0, 5)} />
      <SettingRow k="autoComplete" label="Automatic completion" help={`If on: ${s.reviewWindowDays}-day review window, buyer notified, paused by an open replacement or dispute. Recorded as an administrative completion.`} render={v => v ? 'On' : 'Off'} input={{ from: v => v ? 'on' : 'off', el: (v, set) => <select aria-label="Automatic completion" value={v} onChange={e => set(e.target.value)}><option value="off">Off</option><option value="on">On</option></select> }} toValue={v => v === 'on'} /></Section>
    <Section title="Disputes"><SettingRow k="disputeResponseHours" label="Response deadline (hours)" help="Expiry escalates; it never decides a case." render={v => v + ' h'} input={num()} toValue={toNum(1, 720)} />
      <SettingRow k="appealDays" label="Appeal window (days)" help="Request review of a decision." render={v => v + ' days'} input={num()} toValue={toNum(0, 60)} /></Section>
    <Section title="File retention"><KV items={Object.entries(s.retention).map(([k, v]) => [k, v])} /><p className="xs muted">Retention changes need independent approval. Final periods are a business and legal decision. This demo never purges data.</p>
      {can(db, staff, 'settings.edit') && <Btn size="sm" onClick={() => perform('proposeSetting', { key: 'retention', value: { ...S(db).retention, messages: '3 years (placeholder)' }, reason: 'Align message retention with evidence period (demo)' }, d => proposeSetting(d, d.staff[staff.id], 'retention', { ...S(d).retention, messages: '3 years (placeholder)' }, 'Align message retention with evidence period (demo)'), 'Retention change sent for approval')}>Propose: messages 3 years</Btn>}</Section>
    <Versions keys={['replacementDays', 'replacementAttempts', 'autoComplete', 'disputeResponseHours', 'appealDays', 'retention']} /></>;
}

// ---------- security, health and business reports
export function SASecurity() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['ssec']); if (g) return g;
  return <><PageTitle title="Security and audit" sub="Audit history cannot be edited or deleted. Secrets, codes, full payout credentials and identity document contents are never logged." actions={<ExportButton sensitive name="Audit log" rows={db.audit} cols={[['Time', a => new Date(a.at).toISOString()], ['Actor', a => a.actor], ['Role', a => a.role], ['Action', a => a.action], ['Object', a => a.object], ['Reason', a => a.reason], ['Outcome', a => a.outcome], ['Approval', a => a.approval || '']]} />} />
    <Section title="Security events (simulated)"><Table rows={db.securityEvents} cols={[{ k: 'at', label: 'Time', render: e => fmtDT(e.at) }, { k: 't', label: 'Type', render: e => e.type }, { k: 'w', label: 'Who', render: e => e.who }, { k: 'd', label: 'Detail', render: e => <span className="small">{e.detail}</span> }, { k: 's', label: 'Status', render: e => <Badge tone={e.status === 'Resolved' ? 'ok' : e.status === 'Investigating' ? 'warn' : 'muted'}>{e.status}</Badge> },
      { k: 'x', label: '', render: e => e.status === 'Investigating' && can(db, staff, 'audit.view') && <Btn size="sm" onClick={() => perform('resolveSecurityEvent', { eventId: e.id }, d => O.resolveSecurityEvent(d, staff, e.id), 'Marked resolved')}>Mark resolved</Btn> }]} /></Section>
    <Section title="Sensitive access and exports"><Table rows={db.audit.filter(a => a.sensitive || /Export|Role|Staff|Sessions|Integration|Environment/.test(a.action)).slice(0, 15)} empty={<p className="muted small">None yet.</p>} cols={[{ k: 'at', label: 'Time', render: a => fmtDT(a.at) }, { k: 'ac', label: 'Actor', render: a => a.actor }, { k: 'a', label: 'Action', render: a => a.action }, { k: 'o', label: 'Object', render: a => a.object }, { k: 'r', label: 'Reason', render: a => <span className="small">{a.reason}</span> }]} /></Section>
    <h2 className="sec-h">Audit log</h2>
    <AList id="audit" rows={db.audit} search={a => `${a.actor} ${a.action} ${a.object} ${a.reason} ${a.approval || ''}`} pageSize={12}
      filters={[{ k: 'ac', label: 'Actor', options: [...new Set(db.audit.map(a => a.actor))].map(x => [x, x]), test: (a, v) => a.actor === v }, { k: 'r', label: 'Role', options: [...new Set(db.audit.map(a => a.role))].map(x => [x, x]), test: (a, v) => a.role === v }, { k: 'o', label: 'Outcome', options: [...new Set(db.audit.map(a => a.outcome))].map(x => [x, x]), test: (a, v) => a.outcome === v }, { k: 'd', label: 'Date', options: [['1', 'Last 24 h'], ['7', 'Last 7 days']], test: (a, v) => a.at >= now() - +v * DAY }]}
      sorts={[{ id: 'new', label: 'Newest', fn: (a, b) => b.at - a.at }]}
      cols={[{ k: 'at', label: `Time (${tzName})`, render: a => <span className="xs">{fmtDT(a.at)}</span> }, { k: 'ac', label: 'Actor', render: a => <span className="small">{a.actor}<span className="xs muted block">{a.role}</span></span> }, { k: 'a', label: 'Action', render: a => <b className="small">{a.action}</b> }, { k: 'o', label: 'Object', render: a => <code className="xs">{a.object}</code> }, { k: 'r', label: 'Reason', render: a => <span className="small">{a.reason}</span> }, { k: 'c', label: 'Before → after', render: a => <span className="xs">{a.before || a.after ? `${a.before || '—'} → ${a.after || '—'}` : ''}</span> }, { k: 'ap', label: 'Request ref', render: a => a.approval || '' }, { k: 's', label: 'Outcome', render: a => <Badge tone={a.outcome === 'Success' ? 'ok' : 'warn'}>{a.outcome}</Badge> }]} /></>;
}
export function SAHealth() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['sh']); const [rc, setRc] = useState(false); if (g) return g;
  const failedN = db.notifications.filter(n => n.delivery === 'Failed').length;
  const svc = [['Payment integrations', db.integrations.filter(i => i.enabled).every(i => i.health === 'Operational') ? 'Operational' : 'Degraded', db.integrations.map(i => `${i.name}: ${i.health}`).join('; ')], ['Payout integrations', db.payouts.some(p => p.status === 'Reconciliation required') ? 'Degraded' : 'Operational', `${db.payouts.filter(p => p.status === 'Reconciliation required').length} transfers awaiting reconciliation`], ['Notification delivery', failedN ? 'Degraded' : 'Operational', `${failedN} failed customer email deliveries`], ['Background tasks', db.tasks.some(t => t.status === 'Failed') ? 'Degraded' : 'Operational', `${db.tasks.filter(t => t.status === 'Failed').length} failed tasks`], ['File storage', 'Operational', 'Placeholder files only'], ['Backups', 'Operational', 'Last simulated backup 03:00 UTC; restoration check passed (simulated)']];
  return <><PageTitle title="System health" sub="Every status here is a demo indicator, not measured service performance. No uptime figures are shown." />
    <div className="health">{svc.map(([n, s, d]) => <div key={n} className={'hcard ' + (s === 'Operational' ? 'ok' : 'warn')}><div className="row-between"><b className="small">{n}</b><Badge tone={s === 'Operational' ? 'ok' : 'warn'}>{s}</Badge></div><span className="xs">{d}</span><span className="xs muted">Last checked {fmtDT(now() - 5 * 60e3)} · <Sim>Demo</Sim></span></div>)}</div>
    <Section title="Failed tasks"><Table rows={db.tasks} empty={<p className="muted small">No failed tasks.</p>} cols={[{ k: 't', label: 'Task', render: t => <b className="small">{t.type}</b> }, { k: 'r', label: 'Related record', render: t => <span className="small">{t.refLabel}</span> }, { k: 'a', label: 'Attempts', cls: 'num', render: t => t.attempts }, { k: 'e', label: 'Last error', render: t => <span className="xs">{t.lastError}</span> }, { k: 's', label: 'Status', render: t => <Badge tone={t.status === 'Failed' ? 'bad' : 'ok'}>{t.status}</Badge> },
      { k: 'x', label: 'Next permitted action', render: t => t.status === 'Failed' ? (can(db, staff, 'health.retry') ? <Btn size="sm" onClick={() => perform('retryTask', { taskId: t.id }, d => O.retryTask(d, staff, t.id), 'Retry run')}>Retry safely</Btn> : <span className="xs muted">Needs retry permission</span>) : '—' }]} />
      <p className="xs muted">Retrying a payment status query or notification never creates a financial entry. Uncertain money transfers are reconciled from their own record before any new attempt.</p></Section>
    <Section title="Backup and recovery"><KV items={[['Last backup', 'Today 03:00 UTC (simulated)'], ['Restoration check', 'Passed on a copy (simulated)'], ['Production restore', 'Not available in this prototype']]} /><Btn size="sm" onClick={() => setRc(true)}>View recovery checklist</Btn></Section>
    {rc && <Modal title="Recovery checklist (informational)" onClose={() => setRc(false)}><ol className="small"><li>Declare an incident and freeze money movement.</li><li>Identify the last consistent backup and the event log after it.</li><li>Restore into an isolated environment and reconcile provider events.</li><li>Verify balances against provider statements before reopening.</li><li>Record every step in the audit history.</li></ol><Notice tone="info">Demonstration only. No restore or destructive control exists here.</Notice></Modal>}
  </>;
}
export function SABizReports() {
  const { db, staff } = useApp(); const g = useGate(['sbr']); const [range, setRange] = useState(365); const [grp, setGrp] = useState('seller'); if (g) return g;
  const since = now() - range * DAY; const t = platformTotals(db, e => e.at >= since);
  const groups = grp === 'seller' ? Object.values(db.stores).map(s => ({ id: s.id, label: s.name, f: e => e.store === s.id })) : CATEGORIES.map(c => ({ id: c.id, label: c.name, f: e => db.orders.find(o => o.id === e.order)?.snap.cat === c.id }));
  const rows = groups.map(gp => { const x = platformTotals(db, e => e.at >= since && gp.f(e)); const b = grp === 'seller' ? storeBuckets(db, gp.id) : null; return { id: gp.id, label: gp.label, ...x, b }; }).filter(r => r.gross || r.b?.total);
  const ledgerSeller = db.ledger.filter(e => e.from === 'ext').reduce((a, e) => a + e.amt, 0); const f = sellerFundsAll(db); const all = platformTotals(db);
  const unmatched = db.recon.filter(r => r.status === 'Open');
  return <><PageTitle title="Business reports" sub={`USD. Grouped by transaction event date, last ${range} days, ${tzName}. Order-date reports would be labelled separately.`} actions={<><Seg label="Period" value={range} onChange={setRange} options={[{ id: 30, label: '30 d' }, { id: 365, label: '12 m' }]} /><Seg label="Group" value={grp} onChange={setGrp} options={[{ id: 'seller', label: 'By seller' }, { id: 'category', label: 'By category' }]} /><ExportButton name="Business report" rows={rows} cols={[['Group', r => r.label], ['Gross sales', r => (r.gross / 100).toFixed(2)], ['Refunded', r => (r.refunded / 100).toFixed(2)], ['Net sales', r => (r.net / 100).toFixed(2)], ['Net commission', r => (r.netRevenue / 100).toFixed(2)], ['Seller earnings', r => (r.sellerEarnings / 100).toFixed(2)]]} /></>} />
    <div className="report-grid">{[['Gross sales', t.gross], ['Refunded sales', t.refunded], ['Net sales', t.net], ['Gross commission', t.comm], ['Reversed commission', t.commRev], ['Net platform revenue', t.netRevenue], ['Seller earnings', t.sellerEarnings], ['Held funds (now)', f.held], ['Available funds (now)', f.available], ['Paid payouts (all time)', f.paidOut]].map(([k, c]) => <div key={k} className="report"><span className="xs muted">{k}</span><b>{fmtMoney(c)}</b></div>)}</div>
    <Section title={grp === 'seller' ? 'By seller' : 'By category'}><Table rows={rows} empty={<Empty title="No transactions in this period" />} cols={[{ k: 'l', label: grp === 'seller' ? 'Seller' : 'Category', render: r => <b className="small">{r.label}</b> }, { k: 'g', label: 'Gross', cls: 'num', render: r => <M c={r.gross} /> }, { k: 'r', label: 'Refunded', cls: 'num', render: r => <M c={r.refunded} /> }, { k: 'n', label: 'Net sales', cls: 'num', render: r => <M c={r.net} /> }, { k: 'c', label: 'Net commission', cls: 'num', render: r => <M c={r.netRevenue} /> }, { k: 's', label: 'Seller earnings', cls: 'num', render: r => <M c={r.sellerEarnings} /> }, ...(grp === 'seller' ? [{ k: 'h', label: 'Held', cls: 'num', render: r => <M c={r.b.held} /> }, { k: 'a', label: 'Available', cls: 'num', render: r => <M c={r.b.available} /> }, { k: 'res', label: 'Reserved', cls: 'num', render: r => <M c={r.b.reserved} /> }] : [])]} /></Section>
    <Section title="Reconciliation view (all time)"><KV items={[['Seller earnings credited (ledger)', fmtMoney(ledgerSeller)], ['Gross sales − gross commission (platform)', fmtMoney(all.gross - all.comm)], ['Match', ledgerSeller === all.gross - all.comm ? 'Yes' : 'No: investigate'], ['Seller funds across buckets', `${fmtMoney(f.total)} = pending ${fmtMoney(f.pending)} + held ${fmtMoney(f.held)} + available ${fmtMoney(f.available)} + reserved ${fmtMoney(f.reserved)}`], ['Credited − refund reversals − paid out', fmtMoney(ledgerSeller - f.refunded - f.paidOut) + (ledgerSeller - f.refunded - f.paidOut === f.total ? ' (matches)' : ' (mismatch)')], ['Unmatched provider events', unmatched.length ? unmatched.map(r => `${r.id} ${r.type} ${fmtMoney(r.amountC)}`).join('; ') : 'None']]} /></Section></>;
}
export function SAPolicies() {
  const { db, staff, act, perform } = useApp(); const g = useGate(['spol']); const [dlg, setDlg] = useState(null); const [pv, setPv] = useState(null); if (g) return g;
  return <><PageTitle title="Policies" sub="Draft, review, publish. Orders keep the version accepted at checkout. Placeholder text only; no legal terms are claimed as approved." />
    {db.policies.map(p => <Section key={p.id} title={p.title}><Table rows={p.versions.slice().reverse().map(v => ({ ...v, id: v.v }))} cols={[{ k: 'v', label: 'Version', render: v => 'v' + v.v }, { k: 's', label: 'State', render: v => <Badge tone={{ Published: 'ok', 'In review': 'info', Draft: 'muted' }[v.state] || 'muted'}>{v.state}</Badge> }, { k: 'a', label: 'Author', render: v => v.author }, { k: 'r', label: 'Reviewer', render: v => v.reviewer || v.publishedBy || '—' }, { k: 'e', label: 'Published', render: v => v.publishedAt ? fmtDate(v.publishedAt) : '—' }, { k: 'c', label: 'Orders accepting', cls: 'num', render: v => db.orders.filter(o => o.termsVersion === `Terms v${v.v}`).length }, { k: 'x', label: '', render: v => <div className="row-acts"><Btn size="sm" v="ghost" onClick={() => setPv({ p, v })}>Preview</Btn>{v.state === 'In review' && <Btn size="sm" disabled={!can(db, staff, 'policies.publish')} onClick={() => setDlg(p)}>Publish</Btn>}</div> }]} /></Section>)}
    {pv && <Modal title={`${pv.p.title} v${pv.v.v} (preview)`} onClose={() => setPv(null)}><Notice tone="warn">Placeholder content.</Notice><p>{pv.v.content}</p></Modal>}
    {dlg && <ReasonDialog title={`Publish ${dlg.title}`} intro="Updates the website and creates an audit event. Existing orders keep their accepted version." confirm="Publish" onClose={() => setDlg(null)} onSubmit={v => perform('publishPolicy', { policyId: dlg.id, reason: v.reason }, d => O.publishPolicyDraft(d, staff, dlg.id, v.reason), 'Policy published')} />}
  </>;
}
